// Iconography — Font Awesome (regular) path data, VENDORED into the package as inline
// SVG (see src/lib/icons-data.js, generated by tools/gen-icons.mjs). No Font Awesome
// dependency ships: `@corilus/kernel` installs with zero private deps and builds in CI
// / for external clients without the FA token. No icon font, no network: each icon
// carries its path data, rendered into an inline <svg fill="currentColor"> so it
// inherits color + works offline / file:// / under strict CSP (the juglans bundle
// invariant). Same call shape as before: Icon.name({ size, style }).
//
// Regular style only: nothing in the component set swaps an icon on selection
// (selection reads via accent color + a check affordance + backgrounds), so no
// solid variant is needed. Add one here only if a future component requires it.
// To add/remove an icon: edit ICON_NAMES in tools/gen-icons.mjs, run `npm run
// gen-icons`, then map the new fa* key to a semantic name below.
import { ICON_DATA } from './icons-data.js';

// Render a vendored icon ([width, height, path]) as inline SVG at a pixel size.
// viewBox = "0 0 w h"; the svg is square (size x size) and preserveAspectRatio
// (default xMidYMid meet) fits the glyph centered, so every icon keeps a consistent
// square footprint.
const fa = (data) => (p = {}) => {
  const [w, h, d] = data;
  const size = p.size || 16;
  return (
    <svg width={size} height={size} viewBox={`0 0 ${w} ${h}`} fill="currentColor"
      style={p.style} aria-hidden="true" focusable="false">
      <path d={d} />
    </svg>
  );
};

// Kernel-original view-mode glyphs. `floating` and `bottomsheet` are OFFICIAL Kernel icons
// (no Font Awesome equivalent exists), drawn as inline stroke SVG in the same 24x24 regular
// style as the Kit so the view-switcher set reads as one family. (`sidebar` DOES exist in the
// Kit and uses its flipped variant below, since the assistant docks on the right.)
const S = (props) => (
  <svg width={props.size || 16} height={props.size || 16} viewBox="0 0 24 24" fill="none"
    stroke="currentColor" strokeWidth={props.w || 1.8} strokeLinecap="round" strokeLinejoin="round"
    style={props.style}>{props.children}</svg>
);

export const Icon = {
  // ── Font Awesome (regular) ──
  menu: fa(ICON_DATA.faBars),
  dots: fa(ICON_DATA.faEllipsisVertical),
  close: fa(ICON_DATA.faXmark),
  back: fa(ICON_DATA.faAngleLeft),
  check: fa(ICON_DATA.faCheck),
  plus: fa(ICON_DATA.faPlus),
  add: fa(ICON_DATA.faPlus),
  chat: fa(ICON_DATA.faComment),
  search: fa(ICON_DATA.faMagnifyingGlass),
  user: fa(ICON_DATA.faUser),
  users: fa(ICON_DATA.faUsers),
  mic: fa(ICON_DATA.faMicrophone),
  doc: fa(ICON_DATA.faFile),
  pill: fa(ICON_DATA.faCapsules),
  book: fa(ICON_DATA.faBookBlank),
  flag: fa(ICON_DATA.faFlag),
  help: fa(ICON_DATA.faCircleQuestion),
  chevron: fa(ICON_DATA.faAngleRight),
  fullscreen: fa(ICON_DATA.faExpand),
  send: fa(ICON_DATA.faPaperPlane),
  spark: fa(ICON_DATA.faSparkles),
  arrowUp: fa(ICON_DATA.faArrowUp),
  external: fa(ICON_DATA.faArrowUpRightFromSquare),
  attach: fa(ICON_DATA.faPaperclipVertical),
  agent: fa(ICON_DATA.faRobot),
  code: fa(ICON_DATA.faCode),
  image: fa(ICON_DATA.faImage),
  heart: fa(ICON_DATA.faHeart),
  shield: fa(ICON_DATA.faShieldHalved),
  sidebar: fa(ICON_DATA.faSidebarFlip),   // view-mode: flipped — the assistant docks on the right

  // ── Kernel-original view-mode glyphs (official icons; no Font Awesome equivalent) ──
  floating: (p) => <S {...p}><rect x="2" y="6" width="20" height="14" rx="2" /><path d="M8 6V4" /><path d="M16 6V4" /></S>,
  bottomsheet: (p) => <S {...p}><rect x="3" y="3" width="18" height="18" rx="2" /><path d="M3 14h18" /></S>,
};
