// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { AlertDialog, AlertDialogClose, Btn } from '@corilus/kernel';

export default {
  title: 'Kernel/Atom/Overlay/AlertDialog',
  component: AlertDialog,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Modal that forces a consequential confirmation (Base UI alert-dialog)." } },
  },
};

export const Default = {
  render: () => (
      <AlertDialog title="Delete prescription?" description="This cannot be undone."
        trigger={<Btn variant="secondary">Delete</Btn>}
        actions={<><AlertDialogClose><Btn variant="secondary">Cancel</Btn></AlertDialogClose><Btn tone="error">Delete</Btn></>} />
  ),
};
