// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { AllergyCard } from '@corilus/kernel/clinical';

const ALLERGY = { substance: 'Penicilline', criticality: 'high', reactions: ['Anafylaxie', 'Urticaria', 'Larynxoedeem'], recordedDate: '12-04-2019', lastVerified: 'Maart 2026' };

export default {
  title: 'Kernel/Composite/Clinical/AllergyCard',
  component: AllergyCard,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "FHIR AllergyIntolerance card. Criticality maps to status interpretation (critical/borderline)." } },
  },
};

export const Default = {
  render: () => (
      <AllergyCard data={ALLERGY} stage="sprout" />
  ),
};
