// @hand-authored - hand-crafted story; not regenerated by gen-stories.
// Astryx "Properties" model: ONE Playground sandbox (toggle every combination via
// controls) + a Gallery hero. Detail/action/dismiss are genuinely distinct scenarios
// (they change the anatomy, not just a control value) so they get named Examples too.
import { Banner, Button } from '@corilus/kernel';

export default {
  title: 'Core/Feedback & Status/Banner',
  component: Banner,
  tags: ['autodocs'],
  argTypes: {
    tone: { control: 'select', options: ['neutral', 'info', 'success', 'warning', 'error'], description: 'Semantic color, passed through to Card. Also selects the default icon and the default `live` politeness.', table: { category: 'Appearance' } },
    variant: { control: 'radio', options: ['subtle', 'strong'], description: 'subtle (tinted surface) or strong (solid tone fill).', table: { category: 'Appearance' } },
    appearance: { control: 'select', options: ['filled', 'outline', 'subtle', 'elevated'], description: 'Passthrough to Card’s surface treatment. elevated = Astryx’s "Floating" raised variant.', table: { category: 'Appearance' } },
    fullWidth: { control: 'boolean', description: 'Flush, no-radius, edge-to-edge treatment for a page-level notice.', table: { category: 'Appearance' } },
    title: { control: 'text', description: 'The banner headline.', table: { category: 'Content' } },
    description: { control: 'text', description: 'Supporting text below the title.', table: { category: 'Content' } },
    withAction: { control: 'boolean', description: 'Show a trailing action button.', table: { category: 'Content' } },
    dismissible: { control: 'boolean', description: 'Show the dismiss control (calls onDismiss).', table: { category: 'Content' } },
  },
  parameters: {
    docs: {
      description: {
        component:
          'Persistent status message (info/success/warning/error), composed from Card + Collapsible.\n\n**Import**\n\n```ts\nimport { Banner } from \'@corilus/kernel\'\n```\n\n**Do**\n- Pick tone by message severity: info for updates, success for confirmations, warning for caution, error for problems.\n- Make info/success banners dismissible; keep error banners persistent until resolved.\n\n**Don\'t**\n- Use Banner for an auto-expiring notification - that\'s a Toast (not built yet).\n- Use Banner for a block notice with its own header + body + footer actions row - that\'s the separate `Callout` atom.',
      },
    },
  },
};

const renderBanner = ({ withAction, dismissible, ...rest }) => (
  <Banner
    action={withAction ? <Button size="sm" variant="secondary">Review</Button> : undefined}
    onDismiss={dismissible ? () => {} : undefined}
    {...rest}
  />
);

export const Playground = {
  args: {
    tone: 'info', variant: 'subtle', appearance: 'filled', fullWidth: false,
    title: 'New version available', description: 'Refresh to pick up the latest changes.',
    withAction: true, dismissible: true,
  },
  render: renderBanner,
};

export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', maxWidth: 480 }}>
      <Banner tone="info" title="New version available" description="Refresh to pick up the latest changes." onDismiss={() => {}} />
      <Banner tone="success" title="Changes saved" onDismiss={() => {}} />
      <Banner tone="warning" title="Renewal needed" description="Your certificate expires in 3 days." action={<Button size="sm" variant="secondary">Renew</Button>} />
      <Banner tone="error" title="3 items failed to sync" description="Fix the errors below and try again." />
      <Banner tone="success" variant="strong" appearance="elevated" title="Payment received" onDismiss={() => {}} />
    </div>
  ),
};

export const WithDetail = {
  parameters: { controls: { disable: true } },
  render: () => (
    <Banner
      tone="error"
      title="3 items failed to sync"
      detail={
        <ul style={{ margin: 0, paddingLeft: '1.1rem' }}>
          <li>Patient 4021 - network timeout</li>
          <li>Patient 4088 - validation error</li>
          <li>Patient 4110 - network timeout</li>
        </ul>
      }
    />
  ),
};

export const FullWidth = {
  parameters: { controls: { disable: true }, layout: 'fullscreen' },
  render: () => (
    <Banner fullWidth tone="warning" title="Scheduled maintenance tonight at 22:00" onDismiss={() => {}} />
  ),
};
