// @hand-authored - hand-crafted story; not regenerated by gen-stories.
// Astryx "Properties" model: ONE Playground sandbox + a Gallery hero + a States example.
// (The former Variants / Tones / Sizes / Disabled / Destructive stories are now either
// control combinations in the Playground or rows in the Gallery.)
import { Button } from '@corilus/kernel';

export default {
  title: 'Core/Actions/Button',
  component: Button,
  tags: ['autodocs'],
  argTypes: {
    variant: { control: 'select', options: ['primary', 'secondary', 'tertiary', 'text'], description: 'Emphasis level. Reserve `primary` for the single most important action in a view.', table: { category: 'Appearance', defaultValue: { summary: 'primary' } } },
    tone: { control: 'select', options: ['neutral', 'info', 'success', 'warning', 'error'], description: 'Semantic colour. Use `error` for destructive actions (pair with a confirmation).', table: { category: 'Appearance', defaultValue: { summary: 'neutral' } } },
    size: { control: 'select', options: ['sm', 'md'], description: 'Density step.', table: { category: 'Appearance', defaultValue: { summary: 'md' } } },
    children: { control: 'text', name: 'label', description: 'The button label - describe the action ("Save changes"), not "OK".', table: { category: 'Content' } },
    disabled: { control: 'boolean', description: 'Disables the button.', table: { category: 'Appearance' } },
  },
  parameters: {
    docs: {
      description: {
        component:
          'Text button with variant (emphasis) + tone (semantic color). Reserve `primary` for the single most important action in a view.\n\n**Import**\n\n```ts\nimport { Button } from \'@corilus/kernel\'\n```\n\n**Do**\n- Write labels that describe the action ("Save changes", "Send invite"), not "OK".\n- Use `tone="error"` for destructive actions, behind a confirmation step.\n\n**Don\'t**\n- Place more than one `primary` button in the same view - it dilutes hierarchy.\n- Use a Button for navigation - use a link.\n\n> **Deprecated alias:** `Btn` is a deprecated alias of `Button` — use `Button`. It will be removed in the next major and has no separate story.',
      },
    },
  },
};

// The single sandbox: flip variant / tone / size / disabled in Controls.
export const Playground = {
  args: { variant: 'primary', tone: 'neutral', size: 'md', children: 'Save changes', disabled: false },
};

// Overview hero: emphasis (variant) x semantic colour (tone).
export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
      <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
        {['primary', 'secondary', 'tertiary', 'text'].map(v => (
          <Button key={v} variant={v}>{v}</Button>
        ))}
      </div>
      <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
        {['neutral', 'info', 'success', 'warning', 'error'].map(t => (
          <Button key={t} variant="primary" tone={t}>{t}</Button>
        ))}
      </div>
    </div>
  ),
};

// A meaningfully-distinct example worth its own entry: the destructive + disabled states.
export const States = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
      <Button variant="primary" tone="error">Delete record</Button>
      <Button variant="primary" disabled>Disabled</Button>
      <Button variant="primary" size="sm">Small</Button>
    </div>
  ),
};
