// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { Card, Button, Icon } from '@corilus/kernel';

const React = window.React;

export default {
  title: 'Core/Layout/Card',
  component: Card,
  tags: ['autodocs'],
  argTypes: {
    appearance: { control: 'select', options: ["filled","outline","subtle","elevated"], description: "Surface treatment: filled (panel + border), outline (border only), subtle (no border/fill), elevated (raised ring + shadow, hover-lift).", table: { category: 'Appearance', defaultValue: { summary: "filled" } } },
    tone: { control: 'text', description: "Colour identity: a named status (info/success/warning/error), a data tone (data-1..data-6), or any colour/var. Sets --card-tone (+ tinted surface via [data-tone]).", table: { category: 'Appearance', type: { summary: "string" } } },
    accent: { control: 'select', options: [undefined, "strip", "strip-border"], description: "Opt-in tone-coloured accent (needs a tone): strip = top-edge bar; strip-border also keeps the tone border.", table: { category: 'Appearance' } },
    orientation: { control: 'select', options: ["vertical","horizontal"], description: "Column (default) or row.", table: { category: 'Appearance', defaultValue: { summary: "vertical" } } },
    size: { control: 'select', options: ["sm","md","lg"], description: "Padding density step.", table: { category: 'Appearance', defaultValue: { summary: "md" } } },
    interactive: { control: 'boolean', description: "Renders a focusable <button>. Opt-in only.", table: { category: 'Appearance', type: { summary: "bool" } } },
    selected: { control: 'boolean', description: "Chosen state (accent border via [data-selected]).", table: { category: 'Appearance', type: { summary: "bool" } } },
    dragging: { control: 'boolean', description: "Lifted drag state.", table: { category: 'Appearance', type: { summary: "bool" } } },
    children: { control: 'text', description: "Card.Preview / Card.Header / Card.Body / Card.Footer (+ any content). When `detail` is set, this is the always-visible summary.", table: { category: 'Content', type: { summary: "ReactNode" } } },
  },
  parameters: {
    docs: { description: { component: "Neutral base card: wrapper + appearance + tone + accent-strip + collapse. Fill Preview / Header / Body / Footer; pass `detail` to make it collapsible.\n\n**Import**\n\n```ts\nimport { Card } from '@corilus/kernel'\n```\n\n**Do**\n- Compose the base Card + fill slots; don't hand-roll a card wrapper.\n- For a collapsible card, put the teaser in children and the expandable content in `detail`; keep the summary display-only (actions live in detail).\n- Use accent=\"strip\" (needs a tone) for the vibrant top bar; the accent + icon-tile carry the colour so the body stays light and text stays AA.\n\n**Don't**\n- Nest an interactive Card inside another, or put a button/link in a collapsible card's summary (button-in-button)." } },
  },
};

// ── Icon in a tinted tile (the reference's leading treatment) ──
const IconTile = ({ children }) => (
  <span style={{
    width: 40, height: 40, borderRadius: 'var(--density-radius)',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    background: 'var(--card-tone-tint-strong, var(--surface-sunken))',
    color: 'var(--card-tone-text, var(--text-muted))',
  }}>{children}</span>
);

// ── A tone status label (dot + text) reading the card tone ──
const StatusText = ({ children }) => (
  <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: 'var(--card-tone-text, var(--text-muted))', fontWeight: 'var(--type-weight-semibold)', fontSize: 'var(--typography-caption-md-font-size)' }}>
    <span style={{ width: 7, height: 7, borderRadius: 999, background: 'currentColor' }} />
    {children}
  </span>
);

export const Playground = {
  args: { appearance: "elevated", tone: "info", accent: "strip", orientation: "vertical", size: "md", interactive: false, selected: false, dragging: false },
  render: (args) => (
    <div style={{ maxWidth: 380 }}>
      <Card {...args}>
        <Card.Header
          leading={<IconTile>{Icon.heart({ size: 18 })}</IconTile>}
          title="Blood pressure"
          description="152/94 mmHg — elevated 9 days"
        />
      </Card>
    </div>
  ),
};

// Overview hero: the accent + tone matrix at a glance.
export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 260px)', gap: '0.75rem' }}>
      {[
        { tone: undefined, label: 'neutral' },
        { tone: 'info', label: 'info' },
        { tone: 'success', label: 'success' },
        { tone: 'warning', label: 'warning' },
        { tone: 'error', label: 'error' },
        { tone: 'data-3', label: 'data-3' },
      ].map(({ tone, label }) => (
        <Card key={label} appearance="elevated" tone={tone} accent="strip">
          <Card.Header
            leading={<IconTile>{Icon.chart({ size: 18 })}</IconTile>}
            title={label}
            description="accent=strip"
          />
        </Card>
      ))}
    </div>
  ),
};

// The reference "vitals" pattern: collapsible cards, one open at a time (accordion via
// the controlled expanded/onExpandedChange triad), vibrant strip + icon tile on light bodies.
const VITALS = [
  { id: 'bp', tone: 'error', icon: Icon.heart, title: 'Blood Pressure', status: 'Increasing', value: '152/94', unit: 'mmHg', teaser: '132/82 → 152/94 mmHg — elevated 9 consecutive days' },
  { id: 'hr', tone: 'success', icon: Icon.heart, title: 'Heart Rate', status: 'Stable', value: '74', unit: 'bpm', teaser: '72 → 74 bpm — resting rate unchanged' },
  { id: 'wt', tone: 'warning', icon: Icon.chart, title: 'Weight', status: 'Caution', value: '84.1', unit: 'kg', teaser: '+2.1 kg over 3 weeks — +3% since last visit' },
  { id: 'o2', tone: 'data-1', icon: Icon.chart, title: 'Oxygen Saturation', status: 'Normal', value: '98', unit: '%', teaser: '97 → 98% — within expected range' },
];

function VitalsDemo() {
  const [openId, setOpenId] = React.useState('bp');
  return (
    <div style={{ maxWidth: 420, display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
      {VITALS.map((v) => (
        <Card
          key={v.id}
          appearance="elevated"
          tone={v.tone}
          accent="strip"
          expanded={openId === v.id}
          onExpandedChange={(open) => setOpenId(open ? v.id : null)}
          detail={
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
              <div style={{ height: 96, borderRadius: 'var(--density-radius)', background: 'var(--card-tone-tint, var(--surface-sunken))', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--card-tone-text, var(--text-muted))', fontSize: 'var(--typography-caption-md-font-size)' }}>
                trend chart (slotted content)
              </div>
              <Button size="sm" variant="secondary" tone={v.tone.startsWith('data') ? undefined : v.tone}>Review details</Button>
            </div>
          }
        >
          <Card.Header
            leading={<IconTile>{v.icon({ size: 18 })}</IconTile>}
            title={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>{v.title} <StatusText>{v.status}</StatusText></span>}
            description={<><span style={{ fontSize: 'var(--typography-title-md-font-size)', fontWeight: 'var(--type-weight-bold)', color: 'var(--text-default)' }}>{v.value}</span> <span style={{ color: 'var(--text-faint)' }}>{v.unit}</span><div style={{ marginTop: 2 }}>{v.teaser}</div></>}
          />
        </Card>
      ))}
    </div>
  );
}

export const CollapsibleVitals = {
  parameters: { controls: { disable: true } },
  render: () => <VitalsDemo />,
};
