// @hand-authored - hand-crafted story; not regenerated by gen-stories.
// Card is the "Base Card mechanic": the shared chrome contract (surface / bordered /
// elevated / accent / toneScope / dense, resolved once by resolveCardChrome in
// ../lib/cardChrome.js) that Banner and a framed Collapsible trigger read too - change
// the base here and all three adapt. See the "Base Card" docs section below for the
// chrome contract + the internal slot grid.
import {
  Card, Button, Icon,
  IconPill, StatusPill, TrendChip, ValueDisplay, Sparkline, FieldList, EditChip,
} from '@corilus/kernel';

const React = window.React;

export default {
  title: 'Core/Layout/Card',
  component: Card,
  tags: ['autodocs'],
  argTypes: {
    surface: { control: 'select', options: ['plain', 'tinted', 'none'], description: 'Body fill: plain is pure white/bright (matches Banner); tinted is a light tone wash (mixed toward white for a faint hint when a tone paints the box, else a neutral sunken tint); none is transparent.', table: { category: 'Appearance', defaultValue: { summary: 'plain' } } },
    bordered: { control: 'boolean', description: 'The hairline border.', table: { category: 'Appearance', defaultValue: { summary: 'true' } } },
    elevated: { control: 'boolean', description: 'A floating ambient drop shadow (--elevation-floating) - the same family as `accent` and a collapsible card.', table: { category: 'Appearance', defaultValue: { summary: 'false' } } },
    accent: { control: 'boolean', description: 'A tone-coloured accent strip on the top edge (needs a `tone` to show colour; toneScope="box").', table: { category: 'Appearance', defaultValue: { summary: 'false' } } },
    toneScope: { control: 'radio', options: ['box', 'content'], description: '"box" lets `tone` also paint background/border/strip. "content" keeps the box neutral while the tone stays available to slot content (e.g. an icon tile).', table: { category: 'Appearance', defaultValue: { summary: 'box' } } },
    density: { control: 'select', options: [undefined, 'compact', 'comfortable', 'spacious'], description: 'Density scope: reshapes padding/radius/gap via --density-* tokens. Omit to inherit the ambient density.', table: { category: 'Appearance' } },
    tone: { control: 'select', options: [undefined, 'primary', 'info', 'success', 'warning', 'error', 'data-1', 'data-2', 'data-3', 'data-4', 'data-5', 'data-6'], description: 'Colour identity: "primary" (the brand action colour), a named status (info/success/warning/error), a data tone (data-1..data-6), or any colour/var (not offered as a control option - pass one via code).', table: { category: 'Appearance' } },
    orientation: { control: 'select', options: ['vertical', 'horizontal'], description: 'Column (default) or row - the row form collapses back to a column inside a narrow container (@container, not the viewport).', table: { category: 'Appearance', defaultValue: { summary: 'vertical' } } },
    interactive: { control: 'boolean', description: 'Renders a focusable <button>. Opt-in only.', table: { category: 'Appearance', type: { summary: 'bool' } } },
    selected: { control: 'boolean', description: 'Chosen state (accent border via [data-selected]).', table: { category: 'Appearance', type: { summary: 'bool' } } },
    dragging: { control: 'boolean', description: 'Lifted drag state.', table: { category: 'Appearance', type: { summary: 'bool' } } },
    children: { control: 'text', description: 'Card.Preview / Card.Header / Card.Body / Card.Footer (+ any content). When `detail` is set, this is the always-visible summary.', table: { category: 'Content', type: { summary: 'ReactNode' } } },
  },
  parameters: {
    fitContent: true,
    docs: {
      description: {
        component: [
          'Neutral base card - and the shared **chrome mechanic** the whole card family (Card / Banner / a framed Collapsible trigger) is built on. Owns the wrapper: surface + border + accent-strip + elevation + collapse. Fill Preview / Header / Body / Footer; pass `detail` to make it collapsible.',
          '',
          '**Import**',
          '',
          '```ts',
          "import { Card } from '@corilus/kernel'",
          '```',
          '',
          '## The Base Card mechanic',
          '',
          '`surface` / `bordered` / `elevated` / `accent` / `toneScope` / `dense` are resolved **once**, in JS, by `resolveCardChrome` (`src/lib/cardChrome.js`) into a fixed set of `--card-*` custom properties. CSS never decides chrome by itself - it only *reads* those vars. That is what makes this a shared mechanic rather than a per-component look:',
          '',
          '- **Banner** wraps the same resolver (`edge:"left"`, `neutralFill:"bright"`) - change a chrome rule here and Banner adapts too.',
          '- **Collapsible**’s framed trigger inherits `--card-surface` / `--card-border-color` via ordinary CSS custom-property inheritance, so a Collapsible nested inside a Card reads as the same family, with no props of its own for it.',
          '- Fixes a real bug: the old CSS-only chrome had a class rule and an attribute rule both trying to set the same elevation property at different specificities, so `accent` + the legacy `appearance="elevated"` silently lost the elevation. Now there is exactly one place that decides the final value - see the Chrome matrix section below.',
          '',
          '## The internal slot grid',
          '',
          'The four slots (`Card.Preview` / `Card.Header` / `Card.Body` / `Card.Footer`) are placed with **CSS Grid named areas**, not DOM order - `orientation="vertical"` (default) stacks them in a single column; `orientation="horizontal"` switches to a media column + a stacked text column. An absent slot never leaves a gap (an unoccupied grid row auto-collapses to 0 height; the horizontal media column, being a fixed-width track, uses an explicit `:has()` fallback instead - see `HorizontalNoMedia`).',
          '',
          'A container-query collapse of the horizontal form back to vertical on a narrow container was attempted and reverted: an element cannot be restyled by a `@container` condition evaluated against a container-type it establishes on itself (confirmed empirically here - a pre-existing, identical limitation already affects PatientCard\'s own container queries). A real fix needs a dedicated wrapper element; tracked as a follow-up, not shipped as a rule that silently never fires.',
          '',
          '**Do**',
          '- Compose the base Card + fill slots; don’t hand-roll a card wrapper.',
          '- For a collapsible card, put the teaser in children and the expandable content in `detail`; keep the summary display-only (actions live in detail).',
          '- Use `accent` (needs a tone) for the vibrant top bar; the accent + icon-tile carry the colour so the body stays light and text stays AA.',
          '',
          '**Don’t**',
          '- Nest an interactive Card inside another, or put a button/link in a collapsible card\'s summary (button-in-button).',
        ].join('\n'),
      },
    },
  },
};

// ── Icon in a tinted tile (the reference's leading treatment) ──
const IconTile = ({ children }) => (
  <span style={{
    width: 40, height: 40, borderRadius: 'var(--density-radius)',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    background: 'var(--card-tone-tint-strong, var(--surface-sunken))',
    color: 'var(--card-tone-text, var(--text-muted))',
  }}>{children}</span>
);

export const Playground = {
  args: { surface: 'plain', bordered: true, elevated: true, accent: true, toneScope: 'box', tone: 'info', orientation: 'vertical', interactive: false, selected: false, dragging: false },
  render: (args) => (
    <div style={{ maxWidth: 380 }}>
      <Card {...args}>
        <Card.Header
          leading={<IconTile>{Icon.heart({ size: 18 })}</IconTile>}
          title="Blood pressure"
          description="152/94 mmHg — elevated 9 days"
        />
      </Card>
    </div>
  ),
};

// Overview hero: the tone matrix at a glance (accent + elevated - the shared floating
// shadow family).
export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 260px)', gap: '0.75rem' }}>
      {[
        { tone: undefined, label: 'neutral' },
        { tone: 'primary', label: 'primary' },
        { tone: 'info', label: 'info' },
        { tone: 'success', label: 'success' },
        { tone: 'warning', label: 'warning' },
        { tone: 'error', label: 'error' },
        { tone: 'data-3', label: 'data-3' },
      ].map(({ tone, label }) => (
        <Card key={label} elevated accent tone={tone}>
          <Card.Header
            leading={<IconTile>{Icon.chart({ size: 18 })}</IconTile>}
            title={label}
            description="accent + elevated"
          />
        </Card>
      ))}
    </div>
  ),
};

// ── labeled cell so the matrix reads as a decision table, not a wall of cards ──
const Cell = ({ label, children }) => (
  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
    <span style={{ fontFamily: 'var(--typography-caption-md-font-family)', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>{label}</span>
    {children}
  </div>
);

// The chrome matrix, rendered as labelled cells (mirrors Banner's own Gallery) so a
// reviewer can eyeball whether resolveCardChrome tells the truth - including the
// combination that used to be B-54's known bug.
export const ChromeMatrix = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', maxWidth: 600 }}>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>surface</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Three fills only: plain (pure white, matches Banner), tinted (a faint tone wash), none (transparent).
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
          <Cell label='surface="plain" (default) - pure white'><Card surface="plain"><Card.Body>Plain (white)</Card.Body></Card></Cell>
          <Cell label='surface="none"'><Card surface="none"><Card.Body>No fill</Card.Body></Card></Cell>
          <Cell label='surface="tinted" tone="info"'><Card surface="tinted" tone="info"><Card.Body>Tinted (info)</Card.Body></Card></Cell>
          <Cell label='surface="tinted" tone="warning"'><Card surface="tinted" tone="warning"><Card.Body>Tinted (warning)</Card.Body></Card></Cell>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>accent = border, same saturated ~.500 rung</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          The border now matches the strip colour exactly - one saturated edge weight instead of a soft border plus a vivid strip.
        </p>
        <Card accent bordered tone="warning"><Card.Header title="One weight, not two" description="border-color === strip-color" /></Card>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>elevation ↔ state ladder (hover / press this card)</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Rest = floating; hover lifts to overlay; press drops to raised. A flat, non-elevated interactive card (below) never lifts. See the dedicated <b>Elevation</b> story for the full ladder rendered as static levels.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
          <Card interactive elevated tone="info"><Card.Header title="Elevated + interactive" description="hover -> overlay, press -> raised" /></Card>
          <Card interactive tone="info"><Card.Header title="Flat + interactive" description="hover/press: no elevation change" /></Card>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>selected &amp; focus (two independent signals)</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Selected = accent border + a 2px inset accent ring (box-shadow layer). Focus = a 2px outline ring (a separate channel) - Tab to the interactive card to see it, and note a selected card can show both at once.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
          <Cell label="default"><Card interactive><Card.Header title="Not selected" description="click / tab me" /></Card></Cell>
          <Cell label="selected"><Card interactive selected><Card.Header title="Selected" description="accent border + inset ring" /></Card></Cell>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>accent + elevated - the fixed B-54 regression check</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Both the strip AND the shadow must show together - this combination used to silently drop the shadow.
        </p>
        <Card accent elevated tone="success"><Card.Header title="Both effects at once" description="accent + elevated" /></Card>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>toneScope (tone="warning", accent on)</h4>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
          <Cell label='toneScope="box" (default)'><Card accent tone="warning" toneScope="box"><Card.Body>Box painted</Card.Body></Card></Cell>
          <Cell label='toneScope="content"'><Card accent tone="warning" toneScope="content"><Card.Body>Box stays neutral</Card.Body></Card></Cell>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>the deprecated `appearance` alias still works</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          <Card appearance="outline"><Card.Body>appearance="outline" → surface="none" bordered</Card.Body></Card>
          <Card appearance="subtle"><Card.Body>appearance="subtle" → surface="none" borderless</Card.Body></Card>
          <Card appearance="elevated" accent tone="info"><Card.Header title="appearance=&quot;elevated&quot; + accent" description="the raised-ring look, unchanged for PatientCard" /></Card>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>the deprecated `size` / `dense` aliases still work → `density`</h4>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.5rem' }}>
          <Cell label='size="sm" → compact'><Card size="sm"><Card.Body>size="sm"</Card.Body></Card></Cell>
          <Cell label='dense → compact'><Card dense><Card.Body>dense</Card.Body></Card></Cell>
          <Cell label='density="compact" (preferred)'><Card density="compact"><Card.Body>density="compact"</Card.Body></Card></Cell>
        </div>
      </div>
    </div>
  ),
};

// The reference "vitals" pattern, rebuilt from the base Card + content ATOMS with NO
// inline restyling: the icon-indented identity cluster uses Card.Header's stacked text
// column - leading=IconPill, title + badge=StatusPill (title row), value=ValueDisplay
// size="sm", description=teaser. Compare with the raw markup this used to need.
const VITALS = [
  { id: 'bp', tone: 'error', icon: Icon.heart, title: 'Blood Pressure', statusKind: 'high', status: 'Increasing', value: '152/94', unit: 'mmHg', teaser: '132/82 → 152/94 mmHg — elevated 9 consecutive days' },
  { id: 'hr', tone: 'success', icon: Icon.heart, title: 'Heart Rate', statusKind: 'normal', status: 'Stable', value: '74', unit: 'bpm', teaser: '72 → 74 bpm — resting rate unchanged' },
  { id: 'wt', tone: 'warning', icon: Icon.chart, title: 'Weight', statusKind: 'borderline', status: 'Caution', value: '84.1', unit: 'kg', teaser: '+2.1 kg over 3 weeks — +3% since last visit' },
  { id: 'o2', tone: 'data-1', icon: Icon.chart, title: 'Oxygen Saturation', statusKind: 'normal', status: 'Normal', value: '98', unit: '%', teaser: '97 → 98% — within expected range' },
];

function VitalsDemo() {
  const [openId, setOpenId] = React.useState('bp');
  return (
    <div style={{ maxWidth: 420, display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
      {VITALS.map((v) => (
        <Card
          key={v.id}
          accent
          tone={v.tone}
          expanded={openId === v.id}
          onExpandedChange={(open) => setOpenId(open ? v.id : null)}
          detail={
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
              <div style={{ height: 96, borderRadius: 'var(--density-radius)', background: 'var(--card-tone-tint, var(--surface-sunken))', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--card-tone-text, var(--text-muted))', fontSize: 'var(--typography-caption-md-font-size)' }}>
                trend chart (slotted content)
              </div>
              <Button size="sm" variant="secondary" tone={v.tone.startsWith('data') ? undefined : v.tone}>Review details</Button>
            </div>
          }
        >
          <Card.Header
            leading={<IconPill label={v.title}>{v.icon({ size: 18 })}</IconPill>}
            title={v.title}
            badge={<StatusPill status={v.statusKind} label={v.status} />}
            value={<ValueDisplay value={v.value} unit={v.unit} size="sm" />}
            description={v.teaser}
          />
        </Card>
      ))}
    </div>
  );
}

export const CollapsibleVitals = {
  parameters: { controls: { disable: true } },
  render: () => <VitalsDemo />,
};

// A horizontal media card: the internal slot grid places Preview as a left column
// spanning Header/Body/Footer's stacked rows, by named grid-area (not DOM order).
// NOTE: a container-query collapse back to vertical on a narrow container was
// attempted and reverted - self-styling an element from a @container condition
// evaluated against a container-type IT establishes on itself does not fire in this
// browser (confirmed; a pre-existing, identical bug already exists in PatientCard's
// own container queries) - a real fix needs a wrapper element and is a follow-up.
export const HorizontalMedia = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <Card orientation="horizontal" elevated>
        <Card.Preview>
          <div style={{ width: '100%', height: '100%', minHeight: 120, background: 'var(--surface-sunken)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-faint)' }}>media</div>
        </Card.Preview>
        <Card.Header title="Horizontal card" description="Media column + stacked text, placed by named grid-area." />
        <Card.Footer><Button size="sm" variant="secondary">Learn more</Button></Card.Footer>
      </Card>
    </div>
  ),
};

// The same card with NO Preview: the horizontal template's fixed-width media column
// would otherwise leave a permanent empty gutter (a fixed-width COLUMN track doesn't
// auto-collapse the way an empty ROW does) - the :has() fallback drops it entirely.
export const HorizontalNoMedia = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <Card orientation="horizontal" elevated>
        <Card.Header title="Horizontal, no media" description="Falls back to the vertical single-column template - no empty gutter." />
        <Card.Footer><Button size="sm" variant="secondary">Learn more</Button></Card.Footer>
      </Card>
    </div>
  ),
};

// ── Elevation ladder ────────────────────────────────────────────────────────
// The four shadow rungs, plus how the card's interaction STATES map onto them.
// Because :hover/:active can't be driven reliably headless, each state cell forces
// its elevation via an inline --card-elevation so the levels are visible statically
// (the live hover/press behaviour is the same value applied on the real state).
const ELEVATION_RUNGS = [
  { name: 'raised', role: 'tight contact — grounded card, or the PRESSED/active state' },
  { name: 'floating', role: 'gentle resting lift — an elevated / accent / collapsible card AT REST' },
  { name: 'overlay', role: 'menus, popovers, toasts — and the card HOVER state' },
  { name: 'modal', role: 'dialogs — and the card DRAGGED state' },
];
const CARD_STATES = [
  { label: 'rest (flat)', varVal: '0 0 #0000' },
  { label: 'rest (elevated)', varVal: 'var(--elevation-floating)' },
  { label: 'hover', varVal: 'var(--elevation-overlay)' },
  { label: 'active / press', varVal: 'var(--elevation-raised)' },
  { label: 'dragged', varVal: 'var(--elevation-modal)' },
];

export const Elevation = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', maxWidth: 620 }}>
      <div>
        <h4 style={{ margin: '0 0 0.75rem' }}>The four shadow rungs (a monotonic ladder)</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          {ELEVATION_RUNGS.map((r) => (
            <div key={r.name} style={{ display: 'grid', gridTemplateColumns: '150px 1fr', gap: '1rem', alignItems: 'center' }}>
              <div style={{ height: 56, borderRadius: 'var(--density-radius)', background: 'var(--surface-bright)', boxShadow: `var(--elevation-${r.name})`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--typography-label-md-font-family)', fontWeight: 'var(--type-weight-semibold)' }}>{r.name}</div>
              <span style={{ fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>{r.role}</span>
            </div>
          ))}
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.25rem' }}>Card interaction states → rung</h4>
        <p style={{ margin: '0 0 0.75rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Each cell forces its elevation statically so you can compare the levels. Live, these apply on hover / :active / drag with a gentle ease-out shift.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '1.25rem' }}>
          {CARD_STATES.map((s) => (
            <div key={s.label} style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              <span style={{ fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>{s.label}</span>
              <div className="krnl-card" style={{ '--card-elevation': s.varVal, margin: 0 }}>
                <Card.Body>Card</Card.Body>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  ),
};

// ── Base-card anatomy ───────────────────────────────────────────────────────
// Card is the base of the whole family; every specialised card fills these regions.
// Body is the only region that's conceptually required; everything else is optional.
export const Anatomy = {
  parameters: {
    controls: { disable: true },
    docs: { description: { story: 'Card is the base of the whole card family - Banner, PatientCard, and specialised cards all compose these same regions and inherit the shared chrome. A REAL card (left) with a legend (right). Two alignment contexts: the header text column indents past the leading icon (title-row · value · description, one identity cluster); Body and Footer reset to the full card width. Region-to-region spacing is a consistent --density-gap; the header stack uses --space-1.' } },
  },
  render: () => (
    <div style={{ display: 'grid', gridTemplateColumns: '340px 1fr', gap: '2rem', alignItems: 'start', maxWidth: 760 }}>
      <Card elevated style={{ margin: 0 }}>
        <Card.Preview>
          <div style={{ width: '100%', minHeight: 90, background: 'var(--surface-sunken)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-faint)', fontSize: 'var(--typography-caption-md-font-size)' }}>Card.Preview — media / cover</div>
        </Card.Preview>
        <Card.Header
          leading={<IconPill label="Heart rate">{Icon.heart({ size: 18 })}</IconPill>}
          title="Card.Header title"
          badge={<StatusPill status="high" label="badge" />}
          value={<ValueDisplay value="152/94" unit="mmHg" size="sm" />}
          description="value · description all indent past the icon"
          action={<Button size="sm" variant="secondary">action</Button>}
        />
        <Card.Body><span style={{ color: 'var(--text-muted)', fontSize: 'var(--typography-body-sm-font-size)' }}>Card.Body — full-width content (breaks out of the icon indent).</span></Card.Body>
        <Card.Footer><Button size="sm" variant="secondary">Cancel</Button><Button size="sm">Confirm</Button></Card.Footer>
      </Card>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>Regions</h4>
        <ol style={{ margin: 0, paddingLeft: '1.2rem', display: 'flex', flexDirection: 'column', gap: '0.6rem', fontSize: 'var(--typography-body-sm-font-size)', color: 'var(--text-muted)' }}>
          <li><b style={{ color: 'var(--text-default)' }}>Card.Preview</b> — edge-to-edge media / cover. Optional.</li>
          <li><b style={{ color: 'var(--text-default)' }}>Card.Header</b> — a leading column (icon/avatar) + a stacked <b style={{ color: 'var(--text-default)' }}>text column</b> that all aligns past the icon:
            <ul style={{ margin: '0.35rem 0 0', paddingLeft: '1.1rem' }}>
              <li><code>title</code> + <code>badge</code> — the identity row (a StatusPill / TrendChip)</li>
              <li><code>value</code> — the prominent value line (a ValueDisplay)</li>
              <li><code>description</code> — the muted supporting / teaser line</li>
              <li><code>action</code> — trailing control (far right)</li>
            </ul>
          </li>
          <li><b style={{ color: 'var(--text-default)' }}>Card.Body</b> — the main content, full width. The one region a card is really about.</li>
          <li><b style={{ color: 'var(--text-default)' }}>Card.Footer</b> — a full-width actions row. Optional.</li>
        </ol>
        <p style={{ margin: '1rem 0 0', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-faint)' }}>
          Drop content ATOMS into the header column (IconPill · StatusPill · ValueDisplay) rather than hand-styling markup. Regions are placed by CSS-Grid named areas; chrome is shared with Banner via one resolver — see the Docs page and the Composer story.
        </p>
      </div>
    </div>
  ),
};

// ── Composer ────────────────────────────────────────────────────────────────
// The "how do I drop content atoms into the regions?" sandbox. Each region has a
// control that picks a content-atom from the base set; the render slots the chosen
// atom into Card.Header (leading / title / status / action), Card.Body and Card.Footer.
// This is the fastest way to see which atom goes where — and the code panel shows the
// exact composition. Chrome (surface/tone/accent/bordered/elevated) is wired too.
const LEADING = {
  none: null,
  'IconPill': <IconPill label="Heart rate">{Icon.heart({ size: 18 })}</IconPill>,
};
const STATUS = {
  none: null,
  'StatusPill': <StatusPill status="high" label="Elevated" />,
  'TrendChip': <TrendChip direction="up" value="+3" label="Up by 3" />,
};
const ACTION = {
  none: null,
  'EditChip': <EditChip label="Edit" />,
  'Button': <Button size="sm" variant="secondary">Action</Button>,
};
const VALUE = {
  none: null,
  'ValueDisplay': <ValueDisplay value="152/94" unit="mmHg" size="sm" />,
};
const BODY = {
  none: null,
  'Sparkline': <div style={{ color: 'var(--card-tone-text, var(--action-accent))' }}><Sparkline data={[132, 134, 131, 138, 143, 148, 152]} ariaLabel="Blood pressure trend" /></div>,
  'FieldList': <FieldList items={[{ label: 'Recorded', value: 'Jul 23, 11:42' }, { label: 'Source', value: 'Philips monitor' }]} />,
  'Text': <span style={{ color: 'var(--text-muted)', fontSize: 'var(--typography-body-sm-font-size)' }}>Free-form body text.</span>,
};
const FOOTER = {
  none: null,
  'Actions': <><Button size="sm" variant="secondary">Dismiss</Button><Button size="sm">Review</Button></>,
};

export const Composer = {
  argTypes: {
    surface: { control: 'select', options: ['plain', 'tinted', 'none'], table: { category: 'Chrome' } },
    tone: { control: 'select', options: [undefined, 'primary', 'info', 'success', 'warning', 'error', 'data-1', 'data-2', 'data-3', 'data-4', 'data-5', 'data-6'], table: { category: 'Chrome' } },
    accent: { control: 'boolean', table: { category: 'Chrome' } },
    bordered: { control: 'boolean', table: { category: 'Chrome' } },
    elevated: { control: 'boolean', table: { category: 'Chrome' } },
    leading: { control: 'select', options: Object.keys(LEADING), table: { category: 'Header (indented past the icon)' } },
    title: { control: 'text', table: { category: 'Header (indented past the icon)' } },
    badge: { control: 'select', options: Object.keys(STATUS), table: { category: 'Header (indented past the icon)' } },
    value: { control: 'select', options: Object.keys(VALUE), table: { category: 'Header (indented past the icon)' } },
    description: { control: 'text', table: { category: 'Header (indented past the icon)' } },
    action: { control: 'select', options: Object.keys(ACTION), table: { category: 'Header (indented past the icon)' } },
    body: { control: 'select', options: Object.keys(BODY), table: { category: 'Body (full width)' } },
    footer: { control: 'select', options: Object.keys(FOOTER), table: { category: 'Footer (full width)' } },
  },
  args: {
    surface: 'plain', tone: 'info', accent: true, bordered: true, elevated: true,
    leading: 'IconPill', title: 'Blood pressure', badge: 'StatusPill', value: 'ValueDisplay',
    description: '132/82 → 152/94 mmHg — elevated 9 consecutive days', action: 'none',
    body: 'none', footer: 'none',
  },
  parameters: {
    docs: { description: { story: 'Pick a content-atom for each region and watch the card compose. Note the header column: leading / title+badge / value / description all indent PAST the icon (one identity cluster), while Body and Footer reset to full width. The base content atoms — IconPill, StatusPill, TrendChip, ValueDisplay, Sparkline, FieldList, EditChip (+ Button) — all import from `@corilus/kernel`. Open the Code panel to copy the exact composition.' } },
  },
  render: ({ surface, tone, accent, bordered, elevated, leading, title, badge, value, description, action, body, footer }) => (
    <div style={{ maxWidth: 400 }}>
      <Card surface={surface} tone={tone || undefined} accent={accent} bordered={bordered} elevated={elevated}>
        <Card.Header
          leading={LEADING[leading]}
          title={title}
          badge={STATUS[badge]}
          value={VALUE[value]}
          description={description || undefined}
          action={ACTION[action]}
        />
        {body !== 'none' ? <Card.Body>{BODY[body]}</Card.Body> : null}
        {footer !== 'none' ? <Card.Footer>{FOOTER[footer]}</Card.Footer> : null}
      </Card>
    </div>
  ),
};
