// @hand-authored - hand-crafted story; not regenerated by gen-stories.
// Card is the "Base Card mechanic": the shared chrome contract (surface / bordered /
// elevated / accent / toneScope / dense, resolved once by resolveCardChrome in
// ../lib/cardChrome.js) that Banner and a framed Collapsible trigger read too - change
// the base here and all three adapt. See the "Base Card" docs section below for the
// chrome contract + the internal slot grid.
import { Card, Button, Icon } from '@corilus/kernel';

const React = window.React;

export default {
  title: 'Core/Layout/Card',
  component: Card,
  tags: ['autodocs'],
  argTypes: {
    surface: { control: 'select', options: ['plain', 'tinted', 'none'], description: 'Body fill: plain is pure white/bright (matches Banner); tinted is a light tone wash (mixed toward white for a faint hint when a tone paints the box, else a neutral sunken tint); none is transparent.', table: { category: 'Appearance', defaultValue: { summary: 'plain' } } },
    bordered: { control: 'boolean', description: 'The hairline border.', table: { category: 'Appearance', defaultValue: { summary: 'true' } } },
    elevated: { control: 'boolean', description: 'A floating ambient drop shadow (--elevation-floating) - the same family as `accent` and a collapsible card.', table: { category: 'Appearance', defaultValue: { summary: 'false' } } },
    accent: { control: 'boolean', description: 'A tone-coloured accent strip on the top edge (needs a `tone` to show colour; toneScope="box").', table: { category: 'Appearance', defaultValue: { summary: 'false' } } },
    toneScope: { control: 'radio', options: ['box', 'content'], description: '"box" lets `tone` also paint background/border/strip. "content" keeps the box neutral while the tone stays available to slot content (e.g. an icon tile).', table: { category: 'Appearance', defaultValue: { summary: 'box' } } },
    dense: { control: 'boolean', description: 'A compact density scope (data-density="compact" on this Card).', table: { category: 'Appearance', defaultValue: { summary: 'false' } } },
    tone: { control: 'text', description: 'Colour identity: a named status (info/success/warning/error), a data tone (data-1..data-6), or any colour/var.', table: { category: 'Appearance' } },
    orientation: { control: 'select', options: ['vertical', 'horizontal'], description: 'Column (default) or row - the row form collapses back to a column inside a narrow container (@container, not the viewport).', table: { category: 'Appearance', defaultValue: { summary: 'vertical' } } },
    size: { control: 'select', options: ['sm', 'md', 'lg'], description: 'Padding density step.', table: { category: 'Appearance', defaultValue: { summary: 'md' } } },
    interactive: { control: 'boolean', description: 'Renders a focusable <button>. Opt-in only.', table: { category: 'Appearance', type: { summary: 'bool' } } },
    selected: { control: 'boolean', description: 'Chosen state (accent border via [data-selected]).', table: { category: 'Appearance', type: { summary: 'bool' } } },
    dragging: { control: 'boolean', description: 'Lifted drag state.', table: { category: 'Appearance', type: { summary: 'bool' } } },
    children: { control: 'text', description: 'Card.Preview / Card.Header / Card.Body / Card.Footer (+ any content). When `detail` is set, this is the always-visible summary.', table: { category: 'Content', type: { summary: 'ReactNode' } } },
  },
  parameters: {
    fitContent: true,
    docs: {
      description: {
        component: [
          'Neutral base card - and the shared **chrome mechanic** the whole card family (Card / Banner / a framed Collapsible trigger) is built on. Owns the wrapper: surface + border + accent-strip + elevation + collapse. Fill Preview / Header / Body / Footer; pass `detail` to make it collapsible.',
          '',
          '**Import**',
          '',
          '```ts',
          "import { Card } from '@corilus/kernel'",
          '```',
          '',
          '## The Base Card mechanic',
          '',
          '`surface` / `bordered` / `elevated` / `accent` / `toneScope` / `dense` are resolved **once**, in JS, by `resolveCardChrome` (`src/lib/cardChrome.js`) into a fixed set of `--card-*` custom properties. CSS never decides chrome by itself - it only *reads* those vars. That is what makes this a shared mechanic rather than a per-component look:',
          '',
          '- **Banner** wraps the same resolver (`edge:"left"`, `neutralFill:"bright"`) - change a chrome rule here and Banner adapts too.',
          '- **Collapsible**’s framed trigger inherits `--card-surface` / `--card-border-color` via ordinary CSS custom-property inheritance, so a Collapsible nested inside a Card reads as the same family, with no props of its own for it.',
          '- Fixes a real bug: the old CSS-only chrome had a class rule and an attribute rule both trying to set the same elevation property at different specificities, so `accent` + the legacy `appearance="elevated"` silently lost the elevation. Now there is exactly one place that decides the final value - see the Chrome matrix section below.',
          '',
          '## The internal slot grid',
          '',
          'The four slots (`Card.Preview` / `Card.Header` / `Card.Body` / `Card.Footer`) are placed with **CSS Grid named areas**, not DOM order - `orientation="vertical"` (default) stacks them in a single column; `orientation="horizontal"` switches to a media column + a stacked text column. An absent slot never leaves a gap (an unoccupied grid row auto-collapses to 0 height; the horizontal media column, being a fixed-width track, uses an explicit `:has()` fallback instead - see `HorizontalNoMedia`).',
          '',
          'A container-query collapse of the horizontal form back to vertical on a narrow container was attempted and reverted: an element cannot be restyled by a `@container` condition evaluated against a container-type it establishes on itself (confirmed empirically here - a pre-existing, identical limitation already affects PatientCard\'s own container queries). A real fix needs a dedicated wrapper element; tracked as a follow-up, not shipped as a rule that silently never fires.',
          '',
          '**Do**',
          '- Compose the base Card + fill slots; don’t hand-roll a card wrapper.',
          '- For a collapsible card, put the teaser in children and the expandable content in `detail`; keep the summary display-only (actions live in detail).',
          '- Use `accent` (needs a tone) for the vibrant top bar; the accent + icon-tile carry the colour so the body stays light and text stays AA.',
          '',
          '**Don’t**',
          '- Nest an interactive Card inside another, or put a button/link in a collapsible card\'s summary (button-in-button).',
        ].join('\n'),
      },
    },
  },
};

// ── Icon in a tinted tile (the reference's leading treatment) ──
const IconTile = ({ children }) => (
  <span style={{
    width: 40, height: 40, borderRadius: 'var(--density-radius)',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    background: 'var(--card-tone-tint-strong, var(--surface-sunken))',
    color: 'var(--card-tone-text, var(--text-muted))',
  }}>{children}</span>
);

// ── A tone status label (dot + text) reading the card tone ──
const StatusText = ({ children }) => (
  <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: 'var(--card-tone-text, var(--text-muted))', fontWeight: 'var(--type-weight-semibold)', fontSize: 'var(--typography-caption-md-font-size)' }}>
    <span style={{ width: 7, height: 7, borderRadius: 999, background: 'currentColor' }} />
    {children}
  </span>
);

export const Playground = {
  args: { surface: 'plain', bordered: true, elevated: true, accent: true, toneScope: 'box', dense: false, tone: 'info', orientation: 'vertical', size: 'md', interactive: false, selected: false, dragging: false },
  render: (args) => (
    <div style={{ maxWidth: 380 }}>
      <Card {...args}>
        <Card.Header
          leading={<IconTile>{Icon.heart({ size: 18 })}</IconTile>}
          title="Blood pressure"
          description="152/94 mmHg — elevated 9 days"
        />
      </Card>
    </div>
  ),
};

// Overview hero: the tone matrix at a glance (accent + elevated - the shared floating
// shadow family).
export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 260px)', gap: '0.75rem' }}>
      {[
        { tone: undefined, label: 'neutral' },
        { tone: 'info', label: 'info' },
        { tone: 'success', label: 'success' },
        { tone: 'warning', label: 'warning' },
        { tone: 'error', label: 'error' },
        { tone: 'data-3', label: 'data-3' },
      ].map(({ tone, label }) => (
        <Card key={label} elevated accent tone={tone}>
          <Card.Header
            leading={<IconTile>{Icon.chart({ size: 18 })}</IconTile>}
            title={label}
            description="accent + elevated"
          />
        </Card>
      ))}
    </div>
  ),
};

// ── labeled cell so the matrix reads as a decision table, not a wall of cards ──
const Cell = ({ label, children }) => (
  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
    <span style={{ fontFamily: 'var(--typography-caption-md-font-family)', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>{label}</span>
    {children}
  </div>
);

// The chrome matrix, rendered as labelled cells (mirrors Banner's own Gallery) so a
// reviewer can eyeball whether resolveCardChrome tells the truth - including the
// combination that used to be B-54's known bug.
export const ChromeMatrix = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', maxWidth: 600 }}>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>surface</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Three fills only: plain (pure white, matches Banner), tinted (a faint tone wash), none (transparent).
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
          <Cell label='surface="plain" (default) - pure white'><Card surface="plain"><Card.Body>Plain (white)</Card.Body></Card></Cell>
          <Cell label='surface="none"'><Card surface="none"><Card.Body>No fill</Card.Body></Card></Cell>
          <Cell label='surface="tinted" tone="info"'><Card surface="tinted" tone="info"><Card.Body>Tinted (info)</Card.Body></Card></Cell>
          <Cell label='surface="tinted" tone="warning"'><Card surface="tinted" tone="warning"><Card.Body>Tinted (warning)</Card.Body></Card></Cell>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>accent = border, same saturated ~.500 rung</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          The border now matches the strip colour exactly - one saturated edge weight instead of a soft border plus a vivid strip.
        </p>
        <Card accent bordered tone="warning"><Card.Header title="One weight, not two" description="border-color === strip-color" /></Card>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>elevation ↔ state ladder (hover / press this card)</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Rest = floating; hover lifts to overlay; press drops to raised. A flat, non-elevated interactive card (below) never lifts. See the dedicated <b>Elevation</b> story for the full ladder rendered as static levels.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
          <Card interactive elevated tone="info"><Card.Header title="Elevated + interactive" description="hover -> overlay, press -> raised" /></Card>
          <Card interactive tone="info"><Card.Header title="Flat + interactive" description="hover/press: no elevation change" /></Card>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>selected &amp; focus (two independent signals)</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Selected = accent border + a 2px inset accent ring (box-shadow layer). Focus = a 2px outline ring (a separate channel) - Tab to the interactive card to see it, and note a selected card can show both at once.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
          <Cell label="default"><Card interactive><Card.Header title="Not selected" description="click / tab me" /></Card></Cell>
          <Cell label="selected"><Card interactive selected><Card.Header title="Selected" description="accent border + inset ring" /></Card></Cell>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>accent + elevated - the fixed B-54 regression check</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Both the strip AND the shadow must show together - this combination used to silently drop the shadow.
        </p>
        <Card accent elevated tone="success"><Card.Header title="Both effects at once" description="accent + elevated" /></Card>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>toneScope (tone="warning", accent on)</h4>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
          <Cell label='toneScope="box" (default)'><Card accent tone="warning" toneScope="box"><Card.Body>Box painted</Card.Body></Card></Cell>
          <Cell label='toneScope="content"'><Card accent tone="warning" toneScope="content"><Card.Body>Box stays neutral</Card.Body></Card></Cell>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>the deprecated `appearance` alias still works</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          <Card appearance="outline"><Card.Body>appearance="outline" → surface="none" bordered</Card.Body></Card>
          <Card appearance="subtle"><Card.Body>appearance="subtle" → surface="none" borderless</Card.Body></Card>
          <Card appearance="elevated" accent tone="info"><Card.Header title="appearance=&quot;elevated&quot; + accent" description="the raised-ring look, unchanged for PatientCard" /></Card>
        </div>
      </div>
    </div>
  ),
};

// The reference "vitals" pattern: collapsible cards, one open at a time (accordion via
// the controlled expanded/onExpandedChange triad), vibrant strip + icon tile on light bodies.
const VITALS = [
  { id: 'bp', tone: 'error', icon: Icon.heart, title: 'Blood Pressure', status: 'Increasing', value: '152/94', unit: 'mmHg', teaser: '132/82 → 152/94 mmHg — elevated 9 consecutive days' },
  { id: 'hr', tone: 'success', icon: Icon.heart, title: 'Heart Rate', status: 'Stable', value: '74', unit: 'bpm', teaser: '72 → 74 bpm — resting rate unchanged' },
  { id: 'wt', tone: 'warning', icon: Icon.chart, title: 'Weight', status: 'Caution', value: '84.1', unit: 'kg', teaser: '+2.1 kg over 3 weeks — +3% since last visit' },
  { id: 'o2', tone: 'data-1', icon: Icon.chart, title: 'Oxygen Saturation', status: 'Normal', value: '98', unit: '%', teaser: '97 → 98% — within expected range' },
];

function VitalsDemo() {
  const [openId, setOpenId] = React.useState('bp');
  return (
    <div style={{ maxWidth: 420, display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
      {VITALS.map((v) => (
        <Card
          key={v.id}
          accent
          tone={v.tone}
          expanded={openId === v.id}
          onExpandedChange={(open) => setOpenId(open ? v.id : null)}
          detail={
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
              <div style={{ height: 96, borderRadius: 'var(--density-radius)', background: 'var(--card-tone-tint, var(--surface-sunken))', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--card-tone-text, var(--text-muted))', fontSize: 'var(--typography-caption-md-font-size)' }}>
                trend chart (slotted content)
              </div>
              <Button size="sm" variant="secondary" tone={v.tone.startsWith('data') ? undefined : v.tone}>Review details</Button>
            </div>
          }
        >
          <Card.Header
            leading={<IconTile>{v.icon({ size: 18 })}</IconTile>}
            title={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>{v.title} <StatusText>{v.status}</StatusText></span>}
            description={<><span style={{ fontSize: 'var(--typography-title-md-font-size)', fontWeight: 'var(--type-weight-bold)', color: 'var(--text-default)' }}>{v.value}</span> <span style={{ color: 'var(--text-faint)' }}>{v.unit}</span><div style={{ marginTop: 2 }}>{v.teaser}</div></>}
          />
        </Card>
      ))}
    </div>
  );
}

export const CollapsibleVitals = {
  parameters: { controls: { disable: true } },
  render: () => <VitalsDemo />,
};

// A horizontal media card: the internal slot grid places Preview as a left column
// spanning Header/Body/Footer's stacked rows, by named grid-area (not DOM order).
// NOTE: a container-query collapse back to vertical on a narrow container was
// attempted and reverted - self-styling an element from a @container condition
// evaluated against a container-type IT establishes on itself does not fire in this
// browser (confirmed; a pre-existing, identical bug already exists in PatientCard's
// own container queries) - a real fix needs a wrapper element and is a follow-up.
export const HorizontalMedia = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <Card orientation="horizontal" elevated>
        <Card.Preview>
          <div style={{ width: '100%', height: '100%', minHeight: 120, background: 'var(--surface-sunken)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-faint)' }}>media</div>
        </Card.Preview>
        <Card.Header title="Horizontal card" description="Media column + stacked text, placed by named grid-area." />
        <Card.Footer><Button size="sm" variant="secondary">Learn more</Button></Card.Footer>
      </Card>
    </div>
  ),
};

// The same card with NO Preview: the horizontal template's fixed-width media column
// would otherwise leave a permanent empty gutter (a fixed-width COLUMN track doesn't
// auto-collapse the way an empty ROW does) - the :has() fallback drops it entirely.
export const HorizontalNoMedia = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <Card orientation="horizontal" elevated>
        <Card.Header title="Horizontal, no media" description="Falls back to the vertical single-column template - no empty gutter." />
        <Card.Footer><Button size="sm" variant="secondary">Learn more</Button></Card.Footer>
      </Card>
    </div>
  ),
};

// ── Elevation ladder ────────────────────────────────────────────────────────
// The four shadow rungs, plus how the card's interaction STATES map onto them.
// Because :hover/:active can't be driven reliably headless, each state cell forces
// its elevation via an inline --card-elevation so the levels are visible statically
// (the live hover/press behaviour is the same value applied on the real state).
const ELEVATION_RUNGS = [
  { name: 'raised', role: 'tight contact — grounded card, or the PRESSED/active state' },
  { name: 'floating', role: 'gentle resting lift — an elevated / accent / collapsible card AT REST' },
  { name: 'overlay', role: 'menus, popovers, toasts — and the card HOVER state' },
  { name: 'modal', role: 'dialogs — and the card DRAGGED state' },
];
const CARD_STATES = [
  { label: 'rest (flat)', varVal: '0 0 #0000' },
  { label: 'rest (elevated)', varVal: 'var(--elevation-floating)' },
  { label: 'hover', varVal: 'var(--elevation-overlay)' },
  { label: 'active / press', varVal: 'var(--elevation-raised)' },
  { label: 'dragged', varVal: 'var(--elevation-modal)' },
];

export const Elevation = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', maxWidth: 620 }}>
      <div>
        <h4 style={{ margin: '0 0 0.75rem' }}>The four shadow rungs (a monotonic ladder)</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          {ELEVATION_RUNGS.map((r) => (
            <div key={r.name} style={{ display: 'grid', gridTemplateColumns: '150px 1fr', gap: '1rem', alignItems: 'center' }}>
              <div style={{ height: 56, borderRadius: 'var(--density-radius)', background: 'var(--surface-bright)', boxShadow: `var(--elevation-${r.name})`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--typography-label-md-font-family)', fontWeight: 'var(--type-weight-semibold)' }}>{r.name}</div>
              <span style={{ fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>{r.role}</span>
            </div>
          ))}
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.25rem' }}>Card interaction states → rung</h4>
        <p style={{ margin: '0 0 0.75rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Each cell forces its elevation statically so you can compare the levels. Live, these apply on hover / :active / drag with a gentle ease-out shift.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '1.25rem' }}>
          {CARD_STATES.map((s) => (
            <div key={s.label} style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              <span style={{ fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>{s.label}</span>
              <div className="krnl-card" style={{ '--card-elevation': s.varVal, margin: 0 }}>
                <Card.Body>Card</Card.Body>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  ),
};

// ── Base-card anatomy ───────────────────────────────────────────────────────
// Card is the base of the whole family; every specialised card fills these regions.
// Body is the only region that's conceptually required; everything else is optional.
// A numbered badge keyed to the right-hand legend. `inset` places the badge INSIDE the
// region (for Card.Preview, which clips overflow so a negative-offset badge would be cut);
// the others sit in the padding gutter at a negative offset without clipping.
const AnnotatedRegion = ({ n, inset, children }) => (
  <div style={{ position: 'relative', outline: '1px dashed var(--border-subtle)', outlineOffset: 2, borderRadius: 4 }}>
    <span style={{ position: 'absolute', top: inset ? 6 : -9, left: inset ? 6 : -9, width: 18, height: 18, borderRadius: 999, background: 'var(--action-accent)', color: 'var(--text-on-accent, #fff)', fontSize: 11, fontWeight: 700, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', zIndex: 2 }}>{n}</span>
    {children}
  </div>
);

export const Anatomy = {
  parameters: {
    controls: { disable: true },
    docs: { description: { story: 'Card is the base of the whole card family - Banner, PatientCard, and specialised cards all compose these same regions and inherit the shared chrome. Fill the slots you need; `Card.Body` is the only conceptually required region, the rest are optional.' } },
  },
  render: () => (
    <div style={{ display: 'grid', gridTemplateColumns: '340px 1fr', gap: '2rem', alignItems: 'start', maxWidth: 720 }}>
      <Card elevated style={{ margin: 0 }}>
        <Card.Preview>
          <AnnotatedRegion n={1} inset>
            <div style={{ width: '100%', minHeight: 90, background: 'var(--surface-sunken)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-faint)' }}>media / cover</div>
          </AnnotatedRegion>
        </Card.Preview>
        <AnnotatedRegion n={2}>
          <Card.Header
            leading={<span style={{ width: 36, height: 36, borderRadius: 'var(--density-radius)', background: 'var(--surface-sunken)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}>{Icon.heart({ size: 18 })}</span>}
            title="Title"
            description="leading · title / description · action"
            action={<Button size="sm" variant="secondary">Action</Button>}
          />
        </AnnotatedRegion>
        <AnnotatedRegion n={3}>
          <Card.Body><span style={{ color: 'var(--text-muted)', fontSize: 'var(--typography-body-sm-font-size)' }}>Body — the main content region.</span></Card.Body>
        </AnnotatedRegion>
        <AnnotatedRegion n={4}>
          <Card.Footer><Button size="sm" variant="secondary">Cancel</Button><Button size="sm">Confirm</Button></Card.Footer>
        </AnnotatedRegion>
      </Card>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>Regions</h4>
        <ol style={{ margin: 0, paddingLeft: '1.2rem', display: 'flex', flexDirection: 'column', gap: '0.6rem', fontSize: 'var(--typography-body-sm-font-size)', color: 'var(--text-muted)' }}>
          <li><b style={{ color: 'var(--text-default)' }}>Card.Preview</b> — edge-to-edge media / cover. Optional.</li>
          <li><b style={{ color: 'var(--text-default)' }}>Card.Header</b> — a flex row: leading (icon/avatar) · title + description · trailing action. Optional.</li>
          <li><b style={{ color: 'var(--text-default)' }}>Card.Body</b> — the main content. The one region a card is really about.</li>
          <li><b style={{ color: 'var(--text-default)' }}>Card.Footer</b> — an actions row. Optional.</li>
        </ol>
        <p style={{ margin: '1rem 0 0', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-faint)' }}>
          Regions are placed by CSS-Grid named areas (not DOM order), so orientation="horizontal" re-lays the same slots as a media column beside the text. Chrome (surface / border / accent / elevation) is shared with Banner via one resolver - see the Docs page.
        </p>
      </div>
    </div>
  ),
};
