// @hand-authored - hand-crafted story; not regenerated by gen-stories.
// Astryx "Properties" model: ONE Playground sandbox (toggle every combination via
// controls) + a Gallery hero. The former per-variant stories (WithIcon / Selected /
// Muted / Removable) are now control toggles, not separate tree entries.
import { Chip, Icon } from '@corilus/kernel';

export default {
  title: 'Core/Data Display/Chip',
  component: Chip,
  tags: ['autodocs'],
  argTypes: {
    children: { control: 'text', name: 'label', description: 'The chip label.', table: { category: 'Content' } },
    withIcon: { control: 'boolean', description: 'Show a leading icon (a spark glyph here).', table: { category: 'Content' } },
    selected: { control: 'boolean', description: 'Active / chosen state (e.g. an applied filter).', table: { category: 'Appearance' } },
    muted: { control: 'boolean', description: 'De-emphasised styling for secondary chips.', table: { category: 'Appearance' } },
    removable: { control: 'boolean', description: 'Render a trailing remove affordance (calls onRemove).', table: { category: 'Content' } },
  },
  parameters: {
    docs: {
      description: {
        component:
          'Compact interactive tag: suggestion, citation, filter, or toggle. Icon-optional.\n\n**Import**\n\n```ts\nimport { Chip } from \'@corilus/kernel\'\n```\n\n**Do**\n- Use `selected` for an applied filter or an active toggle in a set.\n- Give `onRemove` only to chips the user can actually dismiss (filters, tokens).\n\n**Don\'t**\n- Use a Chip for a primary action - that is a Button.',
      },
    },
  },
};

const renderChip = ({ withIcon, removable, children, ...rest }) => (
  <Chip
    icon={withIcon ? Icon.spark({ size: 13 }) : undefined}
    onRemove={removable ? () => {} : undefined}
    {...rest}
  >
    {children}
  </Chip>
);

// The single sandbox: flip label / icon / selected / muted / removable in Controls.
export const Playground = {
  args: { children: 'Summarize', withIcon: false, selected: false, muted: false, removable: false },
  render: renderChip,
};

// Overview hero: the meaningful combinations at a glance.
export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
      <Chip>Plain</Chip>
      <Chip icon={Icon.spark({ size: 13 })}>With icon</Chip>
      <Chip selected>Selected</Chip>
      <Chip muted>Muted</Chip>
      <Chip onRemove={() => {}}>Removable</Chip>
      <Chip icon={Icon.spark({ size: 13 })} selected onRemove={() => {}}>All combined</Chip>
    </div>
  ),
};
