// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { ConditionCard } from '@corilus/kernel/clinical';

const COND = { code: 'COPD (J44.9)', clinicalStatus: 'active', onsetDate: '2018', severity: 'Matig', verification: 'Bevestigd', note: 'Stabiel onder GOLD II behandeling.' };

export default {
  title: 'Kernel/Composite/Clinical/ConditionCard',
  component: ConditionCard,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "FHIR Condition card. Status pill follows clinicalStatus mapped to interpretation." } },
  },
};

export const Default = {
  render: () => (
      <ConditionCard data={COND} stage="sprout" />
  ),
};
