// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { DemographicCard } from '@corilus/kernel/clinical';

const PATIENT = { name: 'Mr. Bakker', birthDate: '15-03-1942', age: 84, gender: 'male', identifier: '420315-145-23', gp: 'Dr. Bruno', phone: '+31 6 1234 5678', address: 'Kerkstraat 12, Utrecht', lastVisit: '2 dagen geleden' };

export default {
  title: 'Clinical/Cards/DemographicCard',
  component: DemographicCard,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "FHIR Patient identity card. Seed/Sprout/Shoot. No time-series; attributes flow as a field list." } },
  },
};

export const Default = {
  render: () => (
      <DemographicCard data={PATIENT} stage="sprout" />
  ),
};
