// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { Dialog, DialogClose, Btn, TextInput } from '@corilus/kernel';

export default {
  title: 'Kernel/Atom/Overlay/Dialog',
  component: Dialog,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Modal surface for a focused task or confirmation (Base UI dialog)." } },
  },
};

export const Default = {
  render: () => (
      <Dialog title="Rename file" trigger={<Btn>Rename</Btn>}
        actions={<><DialogClose><Btn variant="secondary">Cancel</Btn></DialogClose><Btn>Save</Btn></>}>
        <TextInput defaultValue="report.pdf" />
      </Dialog>
  ),
};
