// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { useState } from 'react';
import { Dialog, DialogClose, Btn, IconButton, Icon, TextInput } from '@corilus/kernel';

export default {
  title: 'Core/Overlays/Dialog/Dialog',
  component: Dialog,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Modal surface for a focused task or confirmation (Base UI dialog)." } },
  },
};

export const Default = {
  render: () => (
      <Dialog title="Rename file" trigger={<Btn>Rename</Btn>}
        actions={<><DialogClose><Btn variant="secondary">Cancel</Btn></DialogClose><Btn>Save</Btn></>}>
        <TextInput defaultValue="report.pdf" />
      </Dialog>
  ),
};

/* onBack + headerAction — a two-level drill-down inside one dialog. Level 2 gets a back
   control that returns to level 1 instead of closing; a close X sits in the header in
   BOTH levels via headerAction. Note the title changes with the level, but the dialog
   never re-mounts (both are still <BaseDialog.Title>, so aria-labelledby stays wired). */
export const HeaderRow = {
  render: () => {
    const [open, setOpen] = useState(false);
    const [detail, setDetail] = useState(false);
    return (
      <>
        <Btn onClick={() => setOpen(true)}>Open settings</Btn>
        <Dialog open={open} onOpenChange={(o) => { setOpen(o); if (!o) setDetail(false); }}
          title={detail ? 'Billing' : 'Manage assistant'}
          onBack={detail ? () => setDetail(false) : undefined}
          headerAction={<DialogClose><IconButton aria-label="Close">{Icon.close({ size: 15, w: 2 })}</IconButton></DialogClose>}>
          {detail
            ? <p>Plan: Base · 50 credits / month.</p>
            : <Btn variant="secondary" onClick={() => setDetail(true)}>Billing →</Btn>}
        </Dialog>
      </>
    );
  },
};
