// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { DonutGauge, USAGE_THRESHOLDS } from '@corilus/kernel';

export default {
  title: 'Core/Feedback & Status/DonutGauge',
  component: DonutGauge,
  tags: ['autodocs'],
  argTypes: {
    value: { control: { type: 'range', min: 0, max: 100 }, description: "The current level.", table: { category: 'Content', type: { summary: "number" } } },
    max: { control: 'number', description: "The upper bound of the scale.", table: { category: 'Content', defaultValue: { summary: "100" }, type: { summary: "number" } } },
    size: { control: 'number', description: "Diameter in pixels.", table: { category: 'Appearance', defaultValue: { summary: "44" }, type: { summary: "number" } } },
    thickness: { control: 'number', description: "Stroke width in pixels. Defaults to roughly size / 6.", table: { category: 'Appearance', type: { summary: "number" } } },
    tone: { control: 'select', options: [undefined, 'primary', 'info', 'success', 'warning', 'error', 'data-1', 'data-2'], description: "Static fill colour when thresholds are omitted.", table: { category: 'Appearance', type: { summary: "string" } } },
    unbounded: { control: 'boolean', description: "The ring never closes; the trailing end fades instead of a hard edge.", table: { category: 'Appearance', type: { summary: "bool" } } },
    valueText: { control: 'text', description: "The aria-valuetext announced by assistive tech - the ring carries no visible text of its own.", table: { category: 'Accessibility', type: { summary: "string" } } },
  },
  parameters: {
    docs: { description: { component: "A circular level gauge (role=\"meter\") - a compact ring reporting a static quantity, with an optional colour-escalation ramp as it nears a limit. Fills once on mount and holds; never animates on change.\n\n**Import**\n\n```ts\nimport { DonutGauge, USAGE_THRESHOLDS } from '@corilus/kernel'\n```\n\n**Do**\n- Use the exported USAGE_THRESHOLDS (info -> warning at 75% -> error at 90%) as the default escalation ramp, or pass your own.\n- Always supply valueText in real units.\n\n**Don't**\n- Animate the fill, spin, or pulse it - it is a gauge that happens to be round, not a loader." } },
  },
};

export const Playground = {
  args: { value: 31, max: 50, size: 44, thickness: undefined, tone: 'info', unbounded: false, valueText: '31 of 50 credits remaining' },
  render: (args) => <DonutGauge {...args} />,
};

const Cell = ({ label, children }) => (
  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.4rem' }}>
    {children}
    <span style={{ fontFamily: 'var(--typography-caption-md-font-family)', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)', textAlign: 'center' }}>{label}</span>
  </div>
);

export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', maxWidth: 560 }}>
      <div>
        <h4 style={{ margin: '0 0 0.75rem' }}>Static tone (no thresholds)</h4>
        <div style={{ display: 'flex', gap: '1.5rem' }}>
          <Cell label='tone="primary"'><DonutGauge value={64} size={56} tone="primary" valueText="64%" /></Cell>
          <Cell label='tone="success"'><DonutGauge value={64} size={56} tone="success" valueText="64%" /></Cell>
          <Cell label='tone="data-2"'><DonutGauge value={64} size={56} tone="data-2" valueText="64%" /></Cell>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.75rem' }}>Escalating ramp (USAGE_THRESHOLDS: info → warning at 75% → error at 90%)</h4>
        <div style={{ display: 'flex', gap: '1.5rem' }}>
          <Cell label="38% healthy"><DonutGauge value={38} size={56} tone="info" thresholds={USAGE_THRESHOLDS} valueText="38 of 100 used" /></Cell>
          <Cell label="78% approaching"><DonutGauge value={78} size={56} tone="info" thresholds={USAGE_THRESHOLDS} valueText="78 of 100 used" /></Cell>
          <Cell label="97% almost out"><DonutGauge value={97} size={56} tone="info" thresholds={USAGE_THRESHOLDS} valueText="3 of 100 remaining" /></Cell>
          <Cell label="100% out (struck cross)"><DonutGauge value={100} size={56} tone="info" thresholds={USAGE_THRESHOLDS} valueText="No credits left" /></Cell>
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.75rem' }}>unbounded (no ceiling - never closes, even at high values)</h4>
        <div style={{ display: 'flex', gap: '1.5rem' }}>
          <Cell label="12 used, no cap"><DonutGauge value={12} size={56} tone="primary" unbounded valueText="12 used - no cap" /></Cell>
          <Cell label="90 used, still no cap"><DonutGauge value={90} size={56} tone="primary" unbounded valueText="90 used - no cap" /></Cell>
        </div>
      </div>
    </div>
  ),
};
