// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { Accordion, FFSection, Toggle } from '@corilus/kernel';

export default {
  title: 'Core/Utility/FFSection',
  component: FFSection,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Collapsible Feature-flags section (Base UI Accordion item)." } },
  },
};

export const Default = {
  render: () => (
      <Accordion.Root defaultValue={['a']}>
        <FFSection value="a" title="Personalisation">
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <Toggle checked onCheckedChange={() => {}} />
            <span style={{ fontSize: 13 }}>Attach patient context</span>
          </div>
        </FFSection>
      </Accordion.Root>
  ),
};
