// @hand-authored - hand-crafted story; not regenerated by gen-stories.
// Rebuilds @cc/react-components' HighlightCard `Default` + `SectionVariants` examples
// (Common-JS/react-components/src/stories/HightlightCard.stories.tsx) on the kernel's
// composed HighlightCard - see CARD-STRUCTURE-PLAN.md §2 and CARECONNECT-CARD-MAPPING.md.
import {
  HighlightCard, IconButton, IconPill, StatusPill, Chip, FieldList, Icon,
} from '@corilus/kernel';

export default {
  title: 'Core/Data Display/HighlightCard',
  component: HighlightCard,
  tags: ['autodocs'],
  argTypes: {
    tone: { control: 'select', options: ['neutral', 'primary', 'info', 'success', 'warning', 'error', 'data-1', 'data-2', 'data-3'], description: 'Colour identity of the shell, forwarded to the shell Card\'s own `tone`.', table: { category: 'Appearance' } },
    bordered: { control: 'boolean', description: 'The shell\'s hairline border.', table: { category: 'Appearance' } },
    title: { control: 'text', table: { category: 'Header' } },
  },
  parameters: {
    docs: {
      description: {
        component: [
          'A tagged header row over a stack of independently toned, optionally collapsible section-Cards. Composes `Card` + `Stack` - not a new primitive; each section is itself a `Card` (`tone` / `surface="tinted"` / `detail`), so the whole component is Card all the way down.',
          '',
          '**Import**',
          '',
          '```ts',
          "import { HighlightCard } from '@corilus/kernel'",
          '```',
          '',
          '## Sections, not an accordion',
          '',
          'Each entry in `sections` is independently toned, independently highlighted, and independently collapsible - there is no shared "one open at a time" coordination, unlike an Accordion. A section becomes collapsible by setting `collapsible: true`; its header is then a real Base UI trigger button (Change A gives it the right-aligned, down/up chevron for free), so its `actions` render inside the revealed panel rather than the header - putting a button inside the trigger would be a button-in-button.',
        ].join('\n'),
      },
    },
  },
};

const documentIcon = () => Icon.doc({ size: 18 });
const parametersIcon = () => Icon.gear({ size: 18 });
const otherIcon = () => Icon.doc({ size: 18 });

export const Playground = {
  args: { tone: 'info', bordered: true, title: 'Consultation summary' },
  render: (args) => (
    <div style={{ maxWidth: 480 }}>
      <HighlightCard
        {...args}
        leading={<IconPill label="Consult">{Icon.user({ size: 18 })}</IconPill>}
        action={<IconButton aria-label="Edit">{Icon.gear({ size: 16 })}</IconButton>}
        sections={[
          {
            content: (
              <FieldList items={[
                { label: 'Reden', value: 'Follow-up on blood pressure medication.' },
                { label: 'Subjectief', value: 'Patient reports feeling well, no side effects.' },
              ]} />
            ),
          },
          {
            icon: parametersIcon(),
            title: 'Parameters',
            description: 'About parameters',
            tone: 'warning',
            highlight: true,
            collapsible: true,
            showMoreLabel: 'Show more',
            showLessLabel: 'Show less',
            content: 'Blood pressure, heart rate and weight were all recorded at this visit.',
          },
          {
            icon: otherIcon(),
            title: 'Referring practice',
            collapsible: true,
            defaultExpanded: false,
            content: (
              <FieldList items={[
                { label: 'Name', value: 'CENTRUM VOOR MEDISCHE ANALYSE' },
                { label: 'Address', value: 'Oud-Strijderslaan 199, 2200 Herentals, BE' },
                { label: 'Contact', value: '014/28.50.00' },
              ]} />
            ),
          },
        ]}
      />
    </div>
  ),
};

// The @cc "Default" example: a tag + title + one header action, a plain (non-toned,
// non-collapsible) first section, then a highlighted collapsible section and a
// collapsed-by-default one - rebuilt on Card/Stack/FieldList, no react-nanny.
export const Default = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <HighlightCard
        tone="primary"
        leading={<IconPill label="Consult">{Icon.user({ size: 18 })}</IconPill>}
        title="Lorem ipsum dolor sit amet, consectetur adipiscing elit"
        action={<IconButton aria-label="Edit">{Icon.gear({ size: 16 })}</IconButton>}
        sections={[
          {
            content: (
              <FieldList items={[
                { label: 'Reden', value: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
                { label: 'Subjectief', value: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
              ]} />
            ),
          },
          {
            icon: parametersIcon(),
            title: 'Parameters',
            description: 'About parameters',
            highlight: true,
            collapsible: true,
            showMoreLabel: 'Show More',
            showLessLabel: 'Show Less',
            content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet.',
          },
          {
            icon: documentIcon(),
            title: 'Other',
            highlight: true,
            collapsible: true,
            defaultExpanded: false,
            content: (
              <FieldList items={[
                { label: 'Name', value: 'CENTRUM VOOR MEDISCHE ANALYSE' },
                { label: 'NIHII', value: '8/13656/77/998' },
                { label: 'Address', value: 'Oud-Strijderslaan 199, 2200 Herentals, BE' },
                { label: 'Contact', value: '014/28.50.00 (phone)' },
              ]} />
            ),
          },
        ]}
      />
    </div>
  ),
};

// The @cc "SectionVariants" example: sections carry their OWN tone, independent of
// the shell's tone - proves the per-section colour axis.
export const SectionVariants = {
  parameters: {
    controls: { disable: true },
    docs: { description: { story: 'Sections can have their own tone independent of the shell\'s own tone.' } },
  },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', maxWidth: 480 }}>
      <HighlightCard
        tone="primary"
        leading={<IconPill label="Consult">{Icon.user({ size: 18 })}</IconPill>}
        title="Primary shell, mixed section tones"
        action={<IconButton aria-label="Edit">{Icon.gear({ size: 16 })}</IconButton>}
        sections={[
          {
            icon: documentIcon(), title: 'Success Section', tone: 'success',
            content: (
              <FieldList items={[
                { label: 'Status', value: 'This section has a success tone.' },
                { label: 'Colour', value: 'Independent of the shell colour.' },
              ]} />
            ),
          },
          {
            icon: parametersIcon(), title: 'Warning Section', tone: 'warning', highlight: true,
            content: (
              <FieldList items={[
                { label: 'Type', value: 'Warning' },
                { label: 'Note', value: 'This section uses the warning tone.' },
              ]} />
            ),
          },
          {
            icon: documentIcon(), title: 'Danger Section', tone: 'error',
            content: (
              <FieldList items={[
                { label: 'Alert', value: 'This section has a danger (error) tone.' },
                { label: 'Attention', value: 'Requires immediate attention.' },
              ]} />
            ),
          },
        ]}
      />

      <HighlightCard
        tone="data-2"
        leading={<IconPill label="Parameters">{Icon.gear({ size: 18 })}</IconPill>}
        title="Mixed tones, all collapsible"
        sections={[
          { icon: documentIcon(), title: 'Info Section', tone: 'info', collapsible: true, showMoreLabel: 'Show', showLessLabel: 'Hide', content: 'This section uses the info tone.' },
          { icon: documentIcon(), title: 'Accent Section', tone: 'data-3', collapsible: true, showMoreLabel: 'Show', showLessLabel: 'Hide', content: 'This section uses the accent (data-3) tone.' },
          { icon: documentIcon(), title: 'Orange Section', tone: 'data-5', collapsible: true, showMoreLabel: 'Show', showLessLabel: 'Hide', content: 'This section uses the orange (data-5) tone.' },
        ]}
      />
    </div>
  ),
};

// The @cc "SectionBorderBottom" example - a tone-coloured rule under the section
// header instead of Card's usual top strip (a small, honest new CSS rule; see
// CARECONNECT-CARD-MAPPING.md §3, "borderBottom ~ accent, a bottom rule is a small
// CSS add").
export const SectionBorderBottom = {
  parameters: {
    controls: { disable: true },
    docs: { description: { story: 'Sections can draw a bottom rule in their own tone via `borderBottom`.' } },
  },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <HighlightCard
        tone="primary"
        leading={<IconPill label="Consult">{Icon.user({ size: 18 })}</IconPill>}
        title="Sections with bottom rules"
        action={<IconButton aria-label="Edit">{Icon.gear({ size: 16 })}</IconButton>}
        sections={[
          { icon: documentIcon(), title: 'Success Section', tone: 'success', borderBottom: true, content: <FieldList items={[{ label: 'Feature', value: 'Bottom rule in the success tone.' }]} /> },
          { icon: documentIcon(), title: 'Warning Section', tone: 'warning', borderBottom: true, highlight: true, content: <FieldList items={[{ label: 'Type', value: 'Highlighted, with a bottom rule.' }]} /> },
          { icon: documentIcon(), title: 'Danger Section', tone: 'error', borderBottom: true, content: <FieldList items={[{ label: 'Alert', value: 'Bottom rule in the danger (error) tone.' }]} /> },
        ]}
      />
    </div>
  ),
};

// The @cc "VariantsFeatures" example - a HighlightCard with no discrete sections at
// all, just plain `body` content (the CareConnect "no side content" pattern).
export const NoSections = {
  parameters: {
    controls: { disable: true },
    docs: { description: { story: 'A HighlightCard with no discrete sections - plain `body` content only.' } },
  },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <HighlightCard
        leading={<IconPill label="Consult">{Icon.user({ size: 18 })}</IconPill>}
        title="No side content"
        action={<IconButton aria-label="Edit">{Icon.gear({ size: 16 })}</IconButton>}
        body={<FieldList items={[
          { label: 'Reden', value: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
          { label: 'Subjectief', value: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
        ]} />}
      />
    </div>
  ),
};

// A badge in the title, matching the @cc "Bandges" [sic] example.
export const WithBadge = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <HighlightCard
        leading={<IconPill label="Consult">{Icon.user({ size: 18 })}</IconPill>}
        title="Lorem ipsum dolor sit amet, consectetur adipiscing elit"
        badge={<><Chip>Badge</Chip><Chip>Badge 2</Chip></>}
        action={<IconButton aria-label="Edit">{Icon.gear({ size: 16 })}</IconButton>}
        sections={[{
          content: (
            <FieldList items={[
              { label: 'Reden', value: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
              { label: 'Subjectief', value: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
            ]} />
          ),
        }]}
      />
    </div>
  ),
};

// Section-level actions: static (header, left) vs collapsible (relocated into
// `detail` - never the trigger button, avoiding a button-in-button).
export const SectionActions = {
  parameters: {
    controls: { disable: true },
    docs: { description: { story: 'A static section renders `actions` in its header; a collapsible section renders them inside `detail` instead - its header is a real trigger button, so a control can never nest inside it.' } },
  },
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <HighlightCard
        leading={<IconPill label="Consult">{Icon.user({ size: 18 })}</IconPill>}
        title="Section actions"
        sections={[
          {
            icon: documentIcon(), title: 'Static section',
            actions: <StatusPill status="normal" label="Reviewed" />,
            content: 'A static section can safely put actions in its own header.',
          },
          {
            icon: parametersIcon(), title: 'Collapsible section', collapsible: true, highlight: true,
            actions: <StatusPill status="borderline" label="Pending" />,
            content: 'A collapsible section moves actions into the revealed panel instead of the header.',
          },
        ]}
      />
    </div>
  ),
};
