// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { LabResultCard } from '@corilus/kernel/clinical';

const GLUCOSE = { property: 'glucose', value: 7.8, unit: 'mmol/L', status: 'high', low: 3.9, high: 6.1, measuredAt: '07:14 nuchter', trend: { direction: 'up', value: '+0.4' } };

export default {
  title: 'Clinical/Cards/LabResultCard',
  component: LabResultCard,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "FHIR Observation (laboratory) Seed/Sprout. Reference range central; Shoot rare (lab acknowledge pushed to Rooted)." } },
  },
};

export const Default = {
  render: () => (
      <LabResultCard data={GLUCOSE} stage="sprout" />
  ),
};
