// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { Menu, MenuItem, MenuSeparator, IconButton, Icon } from '@corilus/kernel';

export default {
  title: 'Core/Overlays/Menu/Menu',
  component: Menu,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Anchored, dismissible dropdown menu of commands (Base UI menu)." } },
  },
};

export const Default = {
  render: () => (
      <Menu trigger={<IconButton aria-label="Actions">{Icon.dots({ size: 18 })}</IconButton>}>
        <MenuItem onClick={() => {}}>Rename</MenuItem>
        <MenuSeparator />
        <MenuItem onClick={() => {}}>Delete</MenuItem>
      </Menu>
  ),
};
