// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { Meter } from '@corilus/kernel';

export default {
  title: 'Core/Feedback & Status/Meter',
  component: Meter,
  tags: ['autodocs'],
  argTypes: {
    value: { control: { type: 'range', min: 0, max: 100, step: 0.5 }, description: "The current level.", table: { category: 'Content', type: { summary: "number" } } },
    max: { control: 'number', description: "The upper bound of the scale.", table: { category: 'Content', defaultValue: { summary: "100" }, type: { summary: "number" } } },
    tone: { control: 'select', options: [undefined, 'primary', 'info', 'success', 'warning', 'error', 'data-1', 'data-2', 'data-3'], description: "Fill colour. Omit for the default --action-solid fill.", table: { category: 'Appearance', type: { summary: "string" } } },
    size: { control: 'select', options: ["sm","md","lg"], description: "Track thickness: sm 4px, md 6px (default), lg 10px.", table: { category: 'Appearance', defaultValue: { summary: "md" } } },
    unbounded: { control: 'boolean', description: "Fades the fill's trailing edge instead of a hard cap, for a quantity with no real ceiling.", table: { category: 'Appearance', type: { summary: "bool" } } },
    label: { control: 'text', description: "Optional caption above the track. Not the accessible name - see valueText.", table: { category: 'Content', type: { summary: "ReactNode" } } },
    valueText: { control: 'text', description: "The aria-valuetext announced by assistive tech, in real units - not just a bare percentage.", table: { category: 'Accessibility', type: { summary: "string" } } },
  },
  parameters: {
    docs: { description: { component: "A static level or quantity (role=\"meter\") - a quota, balance, or score. Shares Progress's track/fill visual; use Progress instead for a task advancing to completion.\n\n**Import**\n\n```ts\nimport { Meter } from '@corilus/kernel'\n```\n\n**Do**\n- Use for a static quantity - credits remaining, storage used, a risk score - never a task advancing toward completion.\n- Always supply valueText in real units so assistive tech announces the actual meaning.\n\n**Don't**\n- Animate the fill on every value change (a live decrementing \"taxi-meter\" tally) - update it silently between renders." } },
  },
};

export const Playground = {
  args: { value: 1.5, max: 50, size: 'md', tone: 'error', unbounded: false, label: 'Credits', valueText: '1.5 of 50 credits remaining, resets 1 September' },
  render: (args) => <div style={{ maxWidth: 320 }}><Meter {...args} /></div>,
};

// The decision table this component answers: role + valueText (the whole reason
// Meter exists rather than styling Progress fatter), plus the escalation a credit
// balance would ride through as it depletes.
export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', maxWidth: 320 }}>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>Credit-balance escalation (info → warning → error)</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          <Meter value={38} max={100} size="lg" tone="info" label="Healthy" valueText="38 of 100 used" />
          <Meter value={78} max={100} size="lg" tone="warning" label="Approaching" valueText="78 of 100 used, resets 1 September" />
          <Meter value={97} max={100} size="lg" tone="error" label="Almost out" valueText="3 of 100 remaining, resets 1 September" />
          <Meter value={100} max={100} size="lg" tone="error" label="Out" valueText="No credits left, resets 1 September" />
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>unbounded (no ceiling)</h4>
        <Meter value={12} max={100} size="lg" tone="primary" unbounded label="Unlimited tier" valueText="12 credits used - no cap" />
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>role=&quot;meter&quot; + aria-valuetext (inspect the DOM)</h4>
        <p style={{ margin: '0 0 0.5rem', fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>
          Unlike Progress's role="progressbar", every Meter above carries role="meter" and a
          real-units aria-valuetext - the accessibility defect this component exists to fix.
        </p>
      </div>
    </div>
  ),
};
