// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { Popover, PopoverClose, PopoverDescription, Button } from '@corilus/kernel';

export default {
  title: 'Kernel/Atom/Overlay/PopoverClose',
  component: PopoverClose,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'A close control inside a Popover. Must be used within <Popover>.' } },
  },
};

export const Default = {
  render: () => (
    <Popover title="Filters" trigger={<Button variant="secondary">Filter</Button>}>
      <PopoverDescription>Narrow the list.</PopoverDescription>
      <PopoverClose><Button variant="tertiary">Close</Button></PopoverClose>
    </Popover>
  ),
};
