// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { Popover, PopoverDescription, Btn } from '@corilus/kernel';

export default {
  title: 'Kernel/Atom/Overlay/Popover',
  component: Popover,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Anchored, dismissible surface for rich content (Base UI popover)." } },
  },
};

export const Default = {
  render: () => (
      <Popover title="Filters" trigger={<Btn variant="secondary">Filter</Btn>}>
        <PopoverDescription>Narrow the list.</PopoverDescription>
      </Popover>
  ),
};
