// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { Progress } from '@corilus/kernel';

export default {
  title: 'Core/Feedback & Status/Progress',
  component: Progress,
  tags: ['autodocs'],
  argTypes: {
    label: { control: 'text', description: "Caption above the track; also the accessible name. If omitted you must supply aria-label instead.", table: { category: 'Content', type: { summary: "ReactNode" } } },
    value: { control: { type: 'range', min: 0, max: 100 }, description: "Current value (0..max).", table: { category: 'Content', type: { summary: "number" } } },
    max: { control: 'number', description: "Upper bound.", table: { category: 'Content', defaultValue: { summary: '100' }, type: { summary: "number" } } },
    size: { control: 'select', options: ['sm', 'md', 'lg'], description: "Track thickness: sm 4px, md 6px (default), lg 10px.", table: { category: 'Appearance', defaultValue: { summary: 'md' } } },
    tone: { control: 'select', options: [undefined, 'primary', 'info', 'success', 'warning', 'error', 'data-1', 'data-2', 'data-3'], description: "Fill colour. Omit for the default --action-solid fill.", table: { category: 'Appearance' } },
    unbounded: { control: 'boolean', description: "Fades the fill's trailing edge instead of a hard cap.", table: { category: 'Appearance', type: { summary: 'bool' } } },
    'aria-label': { control: 'text', description: "Accessible name when there is no visible label. Exactly one of label / aria-label is required - Base UI names the progressbar only from a mounted label, so a bare bar is otherwise unnamed (WCAG 4.1.2).", table: { category: 'Accessibility', type: { summary: "string" } } },
  },
  parameters: {
    docs: { description: { component: "Determinate progress of a task toward completion (Base UI progress, role=\"progressbar\").\n\n**Import**\n\n```ts\nimport { Progress } from '@corilus/kernel'\n```\n\n**Do**\n- Give every Progress a name: a visible label, or aria-label when the bar stands alone.\n- Use for a task with a knowable percentage (upload, import).\n\n**Don't**\n- Use Progress to report a static level or score (credits, battery, risk) - that's Meter. Progress implies movement toward done." } },
  },
};

export const Playground = {
  args: { label: "Uploading", value: 64, max: 100, size: 'md', tone: undefined, unbounded: false },
  render: (args) => <div style={{ maxWidth: 320 }}><Progress {...args} /></div>,
};

export const Gallery = {
  parameters: { controls: { disable: true } },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', maxWidth: 320 }}>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>size</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          <Progress aria-label="sm" value={64} size="sm" />
          <Progress aria-label="md" value={64} size="md" />
          <Progress aria-label="lg" value={64} size="lg" />
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>tone</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          <Progress aria-label="default" value={64} size="lg" />
          <Progress aria-label="primary" value={64} size="lg" tone="primary" />
          <Progress aria-label="success" value={64} size="lg" tone="success" />
          <Progress aria-label="warning" value={64} size="lg" tone="warning" />
          <Progress aria-label="error" value={64} size="lg" tone="error" />
          <Progress aria-label="data-3" value={64} size="lg" tone="data-3" />
        </div>
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>unbounded</h4>
        <Progress aria-label="unbounded" value={82} size="lg" tone="primary" unbounded />
      </div>
    </div>
  ),
};
