// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
// PropertyList takes data records + a renderItem render-prop, so it needs a real
// composition to be meaningful; hand-authored rather than auto-generated.
import { PropertyList, PatientCard, ValueDisplay } from '@corilus/kernel';

export default {
  title: 'Core/Data Display/PropertyList',
  component: PropertyList,
  tags: ['autodocs'],
  argTypes: {
    layout: { control: 'select', options: ['rows', 'grid', 'columns'], description: 'Arrangement: rows (single-column stack), grid (auto-fit cells), columns (multi-column flow). Layout belongs to the list, not the card.', table: { category: 'Appearance', defaultValue: { summary: 'grid' } } },
    minCard: { control: 'number', description: 'Minimum cell width (px) for grid / column width for columns.', table: { category: 'Appearance', defaultValue: { summary: '240' } } },
    density: { control: 'select', options: ['comfortable', 'compact', 'spacious'], description: 'Overrides the page density for this list only.', table: { category: 'Appearance', defaultValue: { summary: 'comfortable' } } },
    title: { control: 'text', description: 'Optional list heading; shown with a live item count.', table: { category: 'Content' } },
  },
  parameters: {
    docs: {
      description: {
        component:
          "Collection view for sprout-cards. Three layouts (rows / grid / columns); cards keep their intrinsic width-morph. Header slots for filter / sort / action.\n\n**Import**\n\n```ts\nimport { PropertyList } from '@corilus/kernel'\n```",
      },
    },
  },
};

const vitals = [
  { id: 'hr', tone: 'heart', title: 'Hartslag', value: '72', unit: 'bpm' },
  { id: 'rr', tone: 'breath', title: 'Ademhaling', value: '16', unit: '/min' },
  { id: 'spo2', tone: 'oxygen', title: 'Saturatie', value: '98', unit: '%' },
  { id: 'temp', tone: 'temperature', title: 'Temperatuur', value: '37,1', unit: '°C' },
];

const renderVital = (it) => (
  <PatientCard stage="sprout" tone={it.tone} title={it.title} value={<ValueDisplay value={it.value} unit={it.unit} />} />
);

// Controls drive the list layout; the records + renderItem are fixed so it always
// renders real cards.
export const Playground = {
  args: { layout: 'grid', minCard: 240, density: 'comfortable', title: 'Metingen' },
  render: (args) => <PropertyList {...args} items={vitals} renderItem={renderVital} />,
};

export const Rows = {
  parameters: { controls: { disable: true } },
  render: () => <PropertyList title="Metingen" layout="rows" items={vitals} renderItem={renderVital} />,
};
