// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { SproutCard } from '@corilus/kernel';
import { VitalSignCard } from '@corilus/kernel/clinical';

const HR = { property: 'heartRate', value: 74, unit: 'bpm', status: 'normal', history: [70, 72, 68, 73, 71, 73, 74], measuredAt: '09:14', reference: 'rust 64', trend: { direction: 'up', value: '+2' } };

export default {
  title: 'Kernel/Composite/Data display/SproutCard',
  component: SproutCard,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Stateful wrapper that owns the Seed / Sprout / Shoot stage state and applies the cross-stage view-transition animation. Render-prop based; per-object cards stay presentational." } },
  },
};

export const Default = {
  render: () => (
      <SproutCard initialStage="sprout" render={(stage, t) => (
        <VitalSignCard data={HR} stage={stage} onEdit={t.toShoot} onSave={() => t.toSprout()} />
      )} />
  ),
};
