// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { Table } from '@corilus/kernel';

export default {
  title: 'Core/Data Display/Table',
  component: Table,
  tags: ['autodocs'],
  parameters: {
    controls: { disable: true },
    docs: { description: { component: "A real semantic <table> (Table / Caption / Header / Body / Footer / Row / Head / Cell), borderless by default - the first tabular-data primitive in Kernel.\n\n**Import**\n\n```ts\nimport { Table } from '@corilus/kernel'\n```\n\n**Do**\n- Always include a Table.Caption describing the table's content, even if visually hidden.\n- Use Table.Head with `numeric` on any column of figures.\n\n**Don't**\n- Reach for divs styled to look like a grid - use the real element for row/column semantics." } },
  },
};

const ROWS = [
  { name: 'Consult notes (Scribe)', rate: '1 credit each', uses: 21, credits: '21.00' },
  { name: 'Evidence search', rate: '0.25 credits each', uses: 33, credits: '8.25' },
  { name: 'Assistant questions', rate: '1 credit each', uses: 5, credits: '5.00' },
  { name: 'Documents & letters', rate: '0.5 credits each', uses: 7, credits: '3.50' },
];

const LedgerExample = () => (
  <Table>
    <Table.Caption>Credits used this month by AI service</Table.Caption>
    <Table.Header>
      <Table.Row>
        <Table.Head>Use case</Table.Head>
        <Table.Head numeric>Uses</Table.Head>
        <Table.Head numeric>Credits</Table.Head>
      </Table.Row>
    </Table.Header>
    <Table.Body>
      {ROWS.map((r) => (
        <Table.Row key={r.name}>
          <Table.Cell>
            {r.name}
            <div style={{ fontSize: 'var(--typography-caption-md-font-size)', color: 'var(--text-muted)' }}>{r.rate}</div>
          </Table.Cell>
          <Table.Cell numeric>{r.uses}</Table.Cell>
          <Table.Cell numeric>{r.credits}</Table.Cell>
        </Table.Row>
      ))}
    </Table.Body>
    <Table.Footer>
      <Table.Row>
        <Table.Cell>Total</Table.Cell>
        <Table.Cell numeric>66</Table.Cell>
        <Table.Cell numeric>37.75</Table.Cell>
      </Table.Row>
    </Table.Footer>
  </Table>
);

export const Playground = {
  render: () => <div style={{ maxWidth: 480 }}><LedgerExample /></div>,
};

export const Gallery = {
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', maxWidth: 480 }}>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>Borderless, with a numeric column + total row</h4>
        <LedgerExample />
      </div>
      <div>
        <h4 style={{ margin: '0 0 0.5rem' }}>Without a numeric column (left-aligned throughout)</h4>
        <Table>
          <Table.Caption>Recent activity</Table.Caption>
          <Table.Header>
            <Table.Row><Table.Head>Date</Table.Head><Table.Head>Event</Table.Head></Table.Row>
          </Table.Header>
          <Table.Body>
            <Table.Row><Table.Cell>Aug 12</Table.Cell><Table.Cell>Consult note generated</Table.Cell></Table.Row>
            <Table.Row><Table.Cell>Aug 11</Table.Cell><Table.Cell>Evidence search run</Table.Cell></Table.Row>
          </Table.Body>
        </Table>
      </div>
    </div>
  ),
};
