// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { Tabs, Tab, TabList, TabPanel } from '@corilus/kernel';

export default {
  title: 'Kernel/Atom/Navigation/TabList',
  component: TabList,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'The row of tabs with the active indicator. Must be used within <Tabs>.' } },
  },
};

export const Default = {
  render: () => (
    <Tabs defaultValue="overview">
      <TabList>
        <Tab value="overview">Overview</Tab>
        <Tab value="history">History</Tab>
        <Tab value="notes">Notes</Tab>
      </TabList>
      <TabPanel value="overview">Overview content</TabPanel>
      <TabPanel value="history">History content</TabPanel>
      <TabPanel value="notes">Notes content</TabPanel>
    </Tabs>
  ),
};
