// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { Tabs, Tab, TabList, TabPanel } from '@corilus/kernel';

export default {
  title: 'Core/Navigation/Tabs/TabPanel',
  component: TabPanel,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'The content panel for one tab. Must be used within <Tabs>.' } },
  },
};

export const Default = {
  render: () => (
    <Tabs defaultValue="overview">
      <TabList>
        <Tab value="overview">Overview</Tab>
        <Tab value="history">History</Tab>
      </TabList>
      <TabPanel value="overview">Overview content</TabPanel>
      <TabPanel value="history">History content</TabPanel>
    </Tabs>
  ),
};
