// @hand-authored - hand-crafted story; not regenerated by gen-stories.
import { ToggleGroup, ToggleGroupItem } from '@corilus/kernel';

export default {
  title: 'Core/Inputs/Toggle/ToggleGroupItem',
  component: ToggleGroupItem,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'One option inside a ToggleGroup. Must be used within <ToggleGroup>.' } },
  },
};

export const Default = {
  render: () => (
    <ToggleGroup defaultValue={['list']}>
      <ToggleGroupItem value="list">List</ToggleGroupItem>
      <ToggleGroupItem value="grid">Grid</ToggleGroupItem>
      <ToggleGroupItem value="calendar">Calendar</ToggleGroupItem>
    </ToggleGroup>
  ),
};
