// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { Tooltip, IconButton, Icon } from '@corilus/kernel';

export default {
  title: 'Kernel/Atom/Overlay/Tooltip',
  component: Tooltip,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Tooltip wrapper (Base UI)." } },
  },
};

export const Default = {
  render: () => (
      <Tooltip label="Copy"><IconButton aria-label="Copy">{Icon.dots({ size: 16 })}</IconButton></Tooltip>
  ),
};
