// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { Tooltip, IconButton, Icon } from '@corilus/kernel';

export default {
  title: 'Core/Overlays/Tooltip/Tooltip',
  component: Tooltip,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "Tooltip wrapper (Base UI).\n\n> **Deprecated alias:** `Tip` is a deprecated alias of `Tooltip` — use `Tooltip`. It will be removed in the next major and has no separate story." } },
  },
};

export const Default = {
  render: () => (
      <Tooltip label="Copy"><IconButton aria-label="Copy">{Icon.dots({ size: 16 })}</IconButton></Tooltip>
  ),
};
