// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
// Transcript is a scroll container for conversation turns; it needs real ChatBubble
// children to be meaningful, so it is composed here rather than auto-generated.
import { Transcript, ChatBubble } from '@corilus/kernel/chat';

export default {
  title: 'Chat/Transcript',
  component: Transcript,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          "Scrolling conversation container: holds the turns and scrolls the newest anchor (default: the last user bubble) to the top when a turn arrives.\n\n**Import**\n\n```ts\nimport { Transcript } from '@corilus/kernel/chat'\n```\n\n**Do**\n- Drive scrollKey off the thing that marks a new turn (last user index / message count).\n\n**Don't**\n- Reimplement scroll-to-latest per surface - that is what this owns.\n\n**Anatomy**\n- **turns** - The conversation content (children).",
      },
    },
  },
};

const thread = [
  { role: 'user', text: 'Vat het dossier van deze patiënt samen.' },
  { role: 'assistant', text: 'Vrouw, 47 jaar. Actieve diagnoses: type 2 diabetes (2019) en hypertensie. Laatste HbA1c 5,9%. Twee actieve medicaties.' },
  { role: 'user', text: 'Zijn er allergieën?' },
  { role: 'assistant', text: 'Ja - penicilline (hoog risico), met netelroos en angio-oedeem als eerdere reacties.' },
];

export const Default = {
  name: 'Conversation',
  render: () => (
    <div style={{ maxWidth: 480, height: 360 }}>
      <Transcript scrollKey={thread.length}>
        {thread.map((turn, i) => (
          <ChatBubble key={i} role={turn.role}>{turn.text}</ChatBubble>
        ))}
      </Transcript>
    </div>
  ),
};
