// @hand-authored - real fixtures/compositions; not regenerated by gen-stories.
import { VitalSignCard } from '@corilus/kernel/clinical';

const HR = { property: 'heartRate', value: 74, unit: 'bpm', status: 'normal', history: [70, 72, 68, 73, 71, 73, 74], measuredAt: '09:14', reference: 'rust 64', trend: { direction: 'up', value: '+2' } };

export default {
  title: 'Clinical/Cards/VitalSignCard',
  component: VitalSignCard,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: "FHIR Observation (vital-signs) at Seed/Sprout/Shoot. Handles 9 properties incl. blood pressure (multi-component)." } },
  },
};

export const Default = {
  render: () => (
      <VitalSignCard data={HR} stage="sprout" />
  ),
};
