#!/usr/bin/env node
// Vendors the icon path data Kernel uses out of the private Font Awesome kit
// (@awesome.me/kit-c983fdf9da) into a committed, dependency-free data module
// (src/lib/icons-data.js). Run this DEV-ONLY step when adding/removing an icon:
//
//   npm run gen-icons        # needs the FA .npmrc token installed locally
//
// The SHIPPED package has NO Font Awesome dependency - `icons.jsx` reads the
// generated `icons-data.js`, so `@corilus/kernel` installs with zero private deps
// and builds in CI / for external clients without the FA token. The rendered SVG is
// byte-identical (same path data, inlined at build time).
//
// To add an icon: add its `fa*` name to ICON_NAMES below, run this script, then map
// it to a semantic key in `src/lib/icons.jsx`.

import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

// The curated set Kernel uses (classic / regular). Keep in sync with icons.jsx.
const ICON_NAMES = [
  'faPlus', 'faRobot', 'faArrowUp', 'faPaperclipVertical', 'faAngleLeft', 'faBookBlank',
  'faComment', 'faCheck', 'faAngleRight', 'faXmark', 'faCode', 'faFile', 'faEllipsisVertical',
  'faArrowUpRightFromSquare', 'faFlag', 'faExpand', 'faHeart', 'faCircleQuestion', 'faImage',
  'faBars', 'faMicrophone', 'faCapsules', 'faMagnifyingGlass', 'faPaperPlane', 'faShieldHalved',
  'faSparkles', 'faUser', 'faUsers',
  'faSidebarFlip', // view-mode switcher: the assistant docks on the RIGHT, so the flipped variant
];

const kit = await import('@awesome.me/kit-c983fdf9da/icons/classic/regular').catch((e) => {
  console.error('gen-icons: could not load the Font Awesome kit. Install deps with the FA .npmrc token first.');
  console.error(e.message);
  process.exit(1);
});

const entries = [];
const missing = [];
for (const name of ICON_NAMES) {
  const def = kit[name];
  if (!def || !def.icon) { missing.push(name); continue; }
  const [w, h, , , d] = def.icon;
  const path = Array.isArray(d) ? d.join('') : d;
  entries.push([name, w, h, path]);
}
if (missing.length) {
  console.error('gen-icons: names not found in the kit:', missing.join(', '));
  process.exit(1);
}

const __dir = dirname(fileURLToPath(import.meta.url));
const out = join(__dir, '..', 'src', 'lib', 'icons-data.js');

const body = [
  '// GENERATED by tools/gen-icons.mjs - do not edit by hand.',
  '// Vendored Font Awesome (classic/regular) path data for the icons Kernel uses, so the',
  '// shipped package carries NO Font Awesome dependency. Each entry is [width, height, path].',
  '// Regenerate after changing the icon set: `npm run gen-icons` (needs the FA .npmrc token).',
  '',
  'export const ICON_DATA = {',
  ...entries.map(([name, w, h, path]) => `  ${name}: [${w}, ${h}, ${JSON.stringify(path)}],`),
  '};',
  '',
].join('\n');

writeFileSync(out, body);
console.log(`gen-icons: wrote ${entries.length} icons to src/lib/icons-data.js`);
